export const SCREEN_DEFINITIONS = [
  { id: "00-auth", route: "/login", pattern: /^\/login(?:\/)?$/, area: "Access", title: "Secure Workspace Access", eyebrow: "SportsAgentsLab MEF", summary: "Sign in before evidence, execution, or assistant sessions are available.", kind: "auth", stage: "B00", primaryAction: "Continue", agent: false, evidence: false, capability: "Authentication required", alternateStates: ["error", "loading"] },
  { id: "01-workspace-switcher", route: "/workspaces", pattern: /^\/workspaces(?:\/)?$/, area: "Workspace", title: "Workspace Switcher", eyebrow: "Workspace context", summary: "Choose the tenant-scoped workspace that controls the records and permissions in view.", kind: "workspace", stage: "B00", primaryAction: "Continue", agent: false, evidence: false, capability: "Tenant context", alternateStates: ["empty", "error"] },
  { id: "02-command-center", route: "/", pattern: /^\/$/, area: "Command", title: "Command Center", eyebrow: "Command center", summary: "A calm work queue for governed imports, review, evidence, and unresolved dependencies.", kind: "dashboard", stage: "B00+", primaryAction: "Open work queue", agent: true, evidence: true, capability: "No live scientific result", alternateStates: ["loading", "empty", "error"] },
  { id: "03-imports-hub", route: "/imports", pattern: /^\/imports(?:\/)?$/, area: "Imports", title: "Force Plates & Imports", eyebrow: "Imports", summary: "Inspect source artifacts and acquisition readiness without changing the immutable source.", kind: "library", stage: "B01", primaryAction: "Open selected item", agent: true, evidence: true, capability: "Awaiting acquisition processor", alternateStates: ["empty", "error"] },
  { id: "04-import-batch-detail", route: "/imports/batches/:batchId", pattern: /^\/imports\/batches\/[^/]+(?:\/)?$/, area: "Imports", title: "Import Batch Detail", eyebrow: "Import batch", summary: "Review parse and mapping checkpoints before a canonical acquisition can be created.", kind: "detail", stage: "B01", primaryAction: "Open evidence", agent: true, evidence: true, capability: "Parse and map status only", alternateStates: ["loading", "error", "blocked"] },
  { id: "05-source-artifact-detail", route: "/imports/artifacts/:artifactId", pattern: /^\/imports\/artifacts\/[^/]+(?:\/)?$/, area: "Imports", title: "Source Artifact Detail", eyebrow: "Source artifact", summary: "Keep the source object inspectable while showing its current processing boundary.", kind: "detail", stage: "B01", primaryAction: "Open evidence", agent: true, evidence: true, capability: "Source immutable", alternateStates: ["loading", "error", "blocked"] },
  { id: "06-source-mapping", route: "/imports/artifacts/:artifactId/mapping", pattern: /^\/imports\/artifacts\/[^/]+\/mapping(?:\/)?$/, area: "Imports", title: "Source Mapping", eyebrow: "Mapping", summary: "Validate field mapping explicitly. The assistant cannot bypass the review gate or silently mutate a source.", kind: "config", stage: "B01", primaryAction: "Validate and continue", agent: true, evidence: true, capability: "Mapping required", alternateStates: ["blocked"] },
  { id: "07-source-profiles", route: "/imports/sources", pattern: /^\/imports\/sources(?:\/)?$/, area: "Imports", title: "Source & Device Profiles", eyebrow: "Source profiles", summary: "Catalog known source and device profiles without implying that a provider is connected.", kind: "library", stage: "B01", primaryAction: "Open selected item", agent: true, evidence: true, capability: "No providers connected", alternateStates: ["empty", "error"] },
  { id: "08-acquisition-config", route: "/imports/artifacts/:artifactId/acquisition", pattern: /^\/imports\/artifacts\/[^/]+\/acquisition(?:\/)?$/, area: "Imports", title: "Acquisition Configuration", eyebrow: "Acquisition", summary: "Confirm acquisition semantics before a canonical record is eligible for downstream processing.", kind: "config", stage: "B01", primaryAction: "Validate and continue", agent: true, evidence: true, capability: "Configuration required", alternateStates: ["validation-error", "blocked"] },
  { id: "09-trial-library", route: "/trials", pattern: /^\/trials(?:\/)?$/, area: "Trials", title: "Trial Library", eyebrow: "Trials", summary: "Browse trial records and review status. No CMJ measurements are produced by this surface.", kind: "library", stage: "B02", primaryAction: "Open selected item", agent: true, evidence: true, capability: "Awaiting deterministic processor", alternateStates: ["empty", "loading", "error"] },
  { id: "10-trial-detail", route: "/trials/:trialId", pattern: /^\/trials\/[^/]+(?:\/)?$/, area: "Trials", title: "Trial Detail", eyebrow: "Trial record", summary: "Inspect source, review metadata, and evidence links without inventing derived output.", kind: "detail", stage: "B02", primaryAction: "Open evidence", agent: true, evidence: true, capability: "No qualified result", alternateStates: ["loading", "blocked"] },
  { id: "11-trial-qa", route: "/trials/:trialId/qa", pattern: /^\/trials\/[^/]+\/qa(?:\/)?$/, area: "Trials", title: "Trial QA Workspace", eyebrow: "Trial review", summary: "Commit review metadata with author and rationale while leaving the source record unchanged.", kind: "review", stage: "B02", primaryAction: "Commit review metadata", agent: true, evidence: true, capability: "Review required", alternateStates: ["loading", "blocked"] },
  { id: "12-event-review", route: "/trials/:trialId/events", pattern: /^\/trials\/[^/]+\/events(?:\/)?$/, area: "Trials", title: "Event Review", eyebrow: "Events", summary: "Review event annotations as additive metadata. Movement onset, takeoff, and landing remain unavailable here.", kind: "review", stage: "B02", primaryAction: "Commit review metadata", agent: true, evidence: true, capability: "Event processor unavailable", alternateStates: ["empty", "error", "blocked"] },
  { id: "13-override-history", route: "/trials/:trialId/overrides", pattern: /^\/trials\/[^/]+\/overrides(?:\/)?$/, area: "Trials", title: "Override History", eyebrow: "Review history", summary: "Inspect the additive history of human review decisions without rewriting source data.", kind: "log", stage: "B02", primaryAction: "Inspect event", agent: true, evidence: true, capability: "No overrides loaded", alternateStates: ["empty", "error"] },
  { id: "14-session-queue", route: "/sessions", pattern: /^\/sessions(?:\/)?$/, area: "Sessions", title: "Session Queue", eyebrow: "Sessions", summary: "See session review work and qualification gates without automatic session claims.", kind: "library", stage: "B03", primaryAction: "Open selected item", agent: true, evidence: true, capability: "Awaiting session processor", alternateStates: ["empty"] },
  { id: "15-session-detail", route: "/sessions/:sessionId", pattern: /^\/sessions\/[^/]+(?:\/)?$/, area: "Sessions", title: "Session Detail", eyebrow: "Session record", summary: "Inspect session context and evidence links. UI metrics remain unavailable until a governed processor is bound.", kind: "detail", stage: "B03", primaryAction: "Open evidence", agent: true, evidence: true, capability: "No UI metrics", alternateStates: ["loading", "error"] },
  { id: "16-session-adjudication", route: "/sessions/:sessionId/adjudicate", pattern: /^\/sessions\/[^/]+\/adjudicate(?:\/)?$/, area: "Sessions", title: "Session Adjudication", eyebrow: "Adjudication", summary: "Make an explicit qualification decision with reviewer context; no automatic qualification is claimed.", kind: "review", stage: "B03", primaryAction: "Qualify session", agent: true, evidence: true, capability: "Reviewer decision required", alternateStates: ["review-conflict", "blocked"] },
  { id: "17-session-decision-log", route: "/sessions/:sessionId/decisions", pattern: /^\/sessions\/[^/]+\/decisions(?:\/)?$/, area: "Sessions", title: "Session Decision Log", eyebrow: "Decision log", summary: "Inspect decision events and rationale with the source context that led to each entry.", kind: "log", stage: "B03", primaryAction: "Inspect event", agent: true, evidence: true, capability: "No decisions loaded", alternateStates: ["empty", "error"] },
  { id: "18-athlete-directory", route: "/athletes", pattern: /^\/athletes(?:\/)?$/, area: "Athletes", title: "Athlete Directory", eyebrow: "Athletes", summary: "Navigate governed athlete records without turning a measurement surface into a health claim.", kind: "library", stage: "B03+", primaryAction: "Open selected item", agent: true, evidence: true, capability: "No athlete data loaded", alternateStates: ["empty", "error"] },
  { id: "19-athlete-profile", route: "/athletes/:athleteId", pattern: /^\/athletes\/[^/]+(?:\/)?$/, area: "Athletes", title: "Athlete Profile", eyebrow: "Athlete record", summary: "Keep profile context, evidence, and uncertainty visible. This view is not diagnostic.", kind: "detail", stage: "B03+", primaryAction: "Open evidence", agent: true, evidence: true, capability: "No profile loaded", alternateStates: ["loading", "error"] },
  { id: "20-athlete-longitudinal", route: "/athletes/:athleteId/longitudinal", pattern: /^\/athletes\/[^/]+\/longitudinal(?:\/)?$/, area: "Athletes", title: "Athlete Longitudinal", eyebrow: "Longitudinal", summary: "Longitudinal analysis is planned for B04+. The control surface is ready without fabricating a trend.", kind: "longitudinal", stage: "B04+", primaryAction: "Change metric/window", agent: true, evidence: true, capability: "Planned", alternateStates: ["planned-only"] },
  { id: "21-evidence-library", route: "/evidence", pattern: /^\/evidence(?:\/)?$/, area: "Evidence", title: "Evidence Library", eyebrow: "Evidence", summary: "Browse evidence records, provenance, and unresolved links without manufacturing a result.", kind: "library", stage: "B01+", primaryAction: "Open selected item", agent: true, evidence: true, capability: "Evidence loading", alternateStates: ["loading", "empty", "error"] },
  { id: "22-evidence-record", route: "/evidence/:evidenceId", pattern: /^\/evidence\/[^/]+(?:\/)?$/, area: "Evidence", title: "Evidence Record", eyebrow: "Evidence record", summary: "Inspect the record boundary and follow provenance when the link is present.", kind: "evidence", stage: "B01+", primaryAction: "Open provenance", agent: true, evidence: true, capability: "Evidence link required", alternateStates: ["missing-link"] },
  { id: "23-provenance-graph", route: "/evidence/:evidenceId/provenance", pattern: /^\/evidence\/[^/]+\/provenance(?:\/)?$/, area: "Evidence", title: "Provenance Graph", eyebrow: "Provenance", summary: "Trace source, processing, review, and evidence nodes without changing any upstream record.", kind: "graph", stage: "B01+", primaryAction: "Inspect node", agent: true, evidence: true, capability: "Source-linked graph", alternateStates: ["empty", "error"] },
  { id: "24-references-hub", route: "/references", pattern: /^\/references(?:\/)?$/, area: "References", title: "References Hub", eyebrow: "References", summary: "Inspect the definitions and protocols that govern how evidence may be interpreted.", kind: "library", stage: "B01+", primaryAction: "Open selected item", agent: true, evidence: true, capability: "Reference catalog", alternateStates: ["empty", "error"] },
  { id: "25-metrics-dictionary", route: "/references/metrics", pattern: /^\/references\/metrics(?:\/)?$/, area: "References", title: "Metrics Dictionary", eyebrow: "References / metrics", summary: "Keep metric definitions separate from a future typed deterministic tool and its evidence.", kind: "library", stage: "B02+", primaryAction: "Open selected item", agent: true, evidence: true, capability: "Definitions only", alternateStates: ["empty", "error"] },
  { id: "26-protocol-library", route: "/references/protocols", pattern: /^\/references\/protocols(?:\/)?$/, area: "References", title: "Protocol Library", eyebrow: "References / protocols", summary: "Browse protocol definitions and their constraints without asserting a completed test.", kind: "library", stage: "B01+", primaryAction: "Open selected item", agent: true, evidence: true, capability: "No completed tests", alternateStates: ["empty", "error"] },
  { id: "27-method-detail", route: "/references/methods/:methodId", pattern: /^\/references\/methods\/[^/]+(?:\/)?$/, area: "References", title: "Method Detail", eyebrow: "Method", summary: "Inspect a method definition and its provenance requirements before any processor is invoked.", kind: "evidence", stage: "B02+", primaryAction: "Open provenance", agent: true, evidence: true, capability: "Method definition only", alternateStates: ["loading", "error"] },
  { id: "28-report-library", route: "/reports", pattern: /^\/reports(?:\/)?$/, area: "Reports", title: "Report Library", eyebrow: "Reports", summary: "Open evidence-linked report drafts and keep unsupported claims out of the output path.", kind: "library", stage: "B03+", primaryAction: "Open selected item", agent: true, evidence: true, capability: "No report generated", alternateStates: ["empty", "error"] },
  { id: "29-report-builder", route: "/reports/:reportId", pattern: /^\/reports\/[^/]+(?:\/)?$/, area: "Reports", title: "Report Builder", eyebrow: "Report builder", summary: "Compose a report from linked evidence. Unsupported claims stay blocked and visible.", kind: "builder", stage: "B03+", primaryAction: "Preview / export evidence-linked report", agent: true, evidence: true, capability: "Evidence links required", alternateStates: ["forbidden-claim"] },
  { id: "30-agent-memory", route: "/assistant/memory", pattern: /^\/assistant\/memory(?:\/)?$/, area: "Assistant", title: "Assistant Memory", eyebrow: "Assistant", summary: "Review and edit visible preferences. Memory is never evidence and never silently changes a record.", kind: "memory", stage: "B00+", primaryAction: "Edit/delete memory", agent: true, evidence: false, capability: "Preference memory only", alternateStates: ["empty", "error"] },
  { id: "31-notifications", route: "/notifications", pattern: /^\/notifications(?:\/)?$/, area: "Command", title: "Notifications", eyebrow: "Notifications", summary: "Inspect actionable events and unresolved dependencies without hiding uncertainty.", kind: "log", stage: "B00+", primaryAction: "Inspect event", agent: true, evidence: true, capability: "No notifications", alternateStates: ["empty", "error"] },
  { id: "32-audit-log", route: "/audit", pattern: /^\/audit(?:\/)?$/, area: "Command", title: "Audit Log", eyebrow: "Audit", summary: "Keep actor, time, scope, and action visible for every governed change.", kind: "log", stage: "B00+", primaryAction: "Inspect event", agent: true, evidence: true, capability: "Audit trail", alternateStates: ["empty", "error"] },
  { id: "33-settings-workspace", route: "/settings", pattern: /^\/settings(?:\/)?$/, area: "Settings", title: "Workspace Settings", eyebrow: "Settings", summary: "Manage explicit workspace preferences while keeping policy, history, and tenancy boundaries intact.", kind: "settings", stage: "B00+", primaryAction: "Save explicit changes", agent: true, evidence: true, capability: "Configuration surface", alternateStates: ["validation-error", "permission-denied"] },
  { id: "34-roles-permissions", route: "/settings/roles", pattern: /^\/settings\/roles(?:\/)?$/, area: "Settings", title: "Roles & Permissions", eyebrow: "Settings / access", summary: "Inspect role capabilities without weakening authorization or hiding unavailable actions.", kind: "settings", stage: "B00+", primaryAction: "Save explicit changes", agent: true, evidence: true, capability: "Admin policy surface", alternateStates: ["permission-denied", "error"] },
  { id: "35-integrations", route: "/settings/integrations", pattern: /^\/settings\/integrations(?:\/)?$/, area: "Settings", title: "Integrations", eyebrow: "Settings / integrations", summary: "See provider capabilities and degraded states without claiming that a processor is connected.", kind: "settings", stage: "B00+", primaryAction: "Save explicit changes", agent: true, evidence: true, capability: "Provider configuration", alternateStates: ["degraded"] },
  { id: "36-scientific-policies", route: "/settings/scientific", pattern: /^\/settings\/scientific(?:\/)?$/, area: "Settings", title: "Scientific & Claim Policies", eyebrow: "Settings / scientific", summary: "Make claim boundaries visible and explicit. Policy configuration cannot create a scientific result.", kind: "settings", stage: "B00+", primaryAction: "Save explicit changes", agent: true, evidence: true, capability: "Claim policy surface", alternateStates: ["permission-denied", "validation-error"] },
  { id: "37-system-health", route: "/settings/health", pattern: /^\/settings\/health(?:\/)?$/, area: "Settings", title: "System Health", eyebrow: "Settings / health", summary: "Inspect runtime capabilities, job state, and safe degradation paths without exposing secrets.", kind: "health", stage: "B00+", primaryAction: "Open work queue", agent: true, evidence: true, capability: "Safe capability flags", alternateStates: ["loading", "error", "degraded"] }
] as const;

export type ScreenId = (typeof SCREEN_DEFINITIONS)[number]["id"];
export type ScreenDefinition = (typeof SCREEN_DEFINITIONS)[number];
export type ScreenState = "default" | "loading" | "empty" | "error" | "blocked" | "validation-error" | "review-conflict" | "planned-only" | "missing-link" | "forbidden-claim" | "permission-denied" | "degraded";

export const SCREEN_BY_ID = Object.fromEntries(SCREEN_DEFINITIONS.map((screen) => [screen.id, screen])) as Record<ScreenId, ScreenDefinition>;

export const NAVIGATION_SECTIONS = [
  { label: "Command", items: ["02-command-center", "31-notifications", "32-audit-log"] },
  { label: "Work", items: ["03-imports-hub", "09-trial-library", "14-session-queue", "18-athlete-directory"] },
  { label: "Evidence", items: ["21-evidence-library", "24-references-hub", "28-report-library"] },
  { label: "Configure", items: ["30-agent-memory", "33-settings-workspace", "37-system-health"] }
] as const satisfies readonly { label: string; items: readonly ScreenId[] }[];

export function screenForPath(pathname: string): ScreenDefinition {
  if (pathname === "/tests" || pathname.startsWith("/tests/")) return SCREEN_BY_ID["25-metrics-dictionary"];
  if (pathname === "/protocols" || pathname.startsWith("/protocols/")) return SCREEN_BY_ID["24-references-hub"];
  return SCREEN_DEFINITIONS.find((screen) => screen.pattern.test(pathname)) ?? SCREEN_BY_ID["02-command-center"];
}

export function stateFromQuery(value: string | null, definition: ScreenDefinition): ScreenState {
  if (value && (value === "default" || definition.alternateStates.includes(value as never))) return value as ScreenState;
  return "default";
}

export function stateLabel(state: ScreenState): string {
  return state === "default" ? "Awaiting governed data" : state.replaceAll("-", " ");
}
