/* Generated by scripts/generate_models.py. Do not edit manually. */

export type SchemaVersion = "1.0.0";

export type Timestamp = string;

export type NonEmptyString = string;

export type ReasonText = string;

export type SourceArtifactId = string & { readonly __brand: "SourceArtifactId" };

export type ImportAttemptId = string & { readonly __brand: "ImportAttemptId" };

export type CanonicalAcquisitionId = string & { readonly __brand: "CanonicalAcquisitionId" };

export type ConfigurationContractId = string & { readonly __brand: "ConfigurationContractId" };

export type ProtocolContractId = string & { readonly __brand: "ProtocolContractId" };

export type TrialId = string & { readonly __brand: "TrialId" };

export type SessionId = string & { readonly __brand: "SessionId" };

export type MetricObservationId = string & { readonly __brand: "MetricObservationId" };

export type ReferenceEpochId = string & { readonly __brand: "ReferenceEpochId" };

export type InferenceResultId = string & { readonly __brand: "InferenceResultId" };

export type EvidenceManifestId = string & { readonly __brand: "EvidenceManifestId" };

export type PractitionerDecisionId = string & { readonly __brand: "PractitionerDecisionId" };

export type AgentContextId = string & { readonly __brand: "AgentContextId" };

export type AuditEventId = string & { readonly __brand: "AuditEventId" };

export type CommandId = string & { readonly __brand: "CommandId" };

export type JobId = string & { readonly __brand: "JobId" };

export type JobAttemptId = string & { readonly __brand: "JobAttemptId" };

export type ProgressEventId = string & { readonly __brand: "ProgressEventId" };

export type IdempotencyKey = string;

export type MetricDefinitionId = string;

export type ChannelId = string;

export type SourceObservationId = string & { readonly __brand: "SourceObservationId" };

export type CanonicalMappingManifestId = string & { readonly __brand: "CanonicalMappingManifestId" };

export type CanonicalIntegrityFindingId = string & { readonly __brand: "CanonicalIntegrityFindingId" };

export type Sha256 = string;

export type SemanticState = "KNOWN" | "UNKNOWN" | "UNRESOLVED" | "UNSUPPORTED" | "NOT_APPLICABLE" | "ABSENT";

export type QualityState = "QUALIFIED" | "UNQUALIFIED" | "UNKNOWN" | "UNRESOLVED" | "UNSUPPORTED" | "NOT_APPLICABLE" | "REJECTED" | "REVIEW_REQUIRED";

export type EntityType = "SourceArtifact" | "ImportAttempt" | "CanonicalAcquisition" | "ConfigurationContract" | "ProtocolContract" | "Trial" | "Session" | "MetricObservation" | "ReferenceEpoch" | "InferenceResult" | "EvidenceManifest" | "PractitionerDecision" | "AgentContext" | "AuditEvent" | "Command" | "Job" | "JobAttempt" | "ProgressEvent";

export type ErrorCode = "VALIDATION_ERROR" | "UNKNOWN_ENTITY_TYPE" | "UNKNOWN_ENUM_VALUE" | "UNSUPPORTED_SCHEMA_VERSION" | "UNKNOWN_SCHEMA_VERSION" | "MISSING_REQUIRED_FIELD" | "INVALID_IDENTIFIER" | "INVALID_TIMESTAMP" | "INVALID_HASH" | "INVALID_STATE_TRANSITION_INPUT" | "UNRESOLVED_REFERENCE" | "CONFLICTING_METADATA" | "UNSUPPORTED_CONFIGURATION" | "INCOMPATIBLE_CONTRACT_VERSION" | "UNKNOWN_GOVERNED_FIELD" | "INVALID_EVIDENCE_REFERENCE" | "INVALID_UNIT" | "INVALID_TYPE" | "FORBIDDEN_FIELD" | "FORBIDDEN_AUTHORITY_COMBINATION";

export interface ContractError {
  readonly taxonomy_version: SchemaVersion;
  readonly code: ErrorCode;
  readonly message: ReasonText;
  readonly path: string;
}

export interface EvidenceReference {
  readonly evidence_manifest_id: EvidenceManifestId;
  readonly component: NonEmptyString;
  readonly locator: NonEmptyString;
  readonly content_hash?: Sha256;
}

export interface ReasonReference {
  readonly code: string;
  readonly description: ReasonText;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface SemanticDeclaration {
  readonly state: SemanticState;
  readonly value?: NonEmptyString;
  readonly reason?: ReasonText;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface Unit {
  readonly system: "SI" | "NATIVE";
  readonly symbol: string;
}

export interface UnitDeclaration {
  readonly state: SemanticState;
  readonly unit?: Unit;
  readonly reason?: ReasonText;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface ConditionObservation {
  readonly condition: "BILATERAL" | "UNLOADED" | "HANDS_ON_HIPS" | "COUNTERMOVEMENT_JUMP";
  readonly observation_state: "CONFIRMED" | "NOT_CONFIRMED" | "UNKNOWN" | "UNRESOLVED" | "UNSUPPORTED" | "NOT_APPLICABLE";
  readonly authority_type: "HUMAN_PRACTITIONER" | "MACHINE_OBSERVED";
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface Channel {
  readonly channel_id: ChannelId;
  readonly physical_quantity: SemanticDeclaration;
  readonly unit: UnitDeclaration;
  readonly axis: SemanticDeclaration;
  readonly sign_convention: SemanticDeclaration;
  readonly sample_time: SemanticDeclaration;
  readonly quality_state: QualityState;
}

export interface SourceMapping {
  readonly channel_id: ChannelId;
  readonly source_label: NonEmptyString;
  readonly mapping_state: SemanticState;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface CanonicalTransformation {
  readonly kind: "IDENTITY" | "UNIT_CONVERSION" | "SIGN_FLIP" | "LINEAR_SCALE";
  readonly scale: number;
  readonly offset: number;
  readonly source_unit?: Unit;
  readonly target_unit?: Unit;
  readonly source_axis?: NonEmptyString;
  readonly target_axis?: NonEmptyString;
}

export interface CanonicalChannel {
  readonly channel_id: ChannelId;
  readonly physical_quantity: SemanticDeclaration;
  readonly unit: UnitDeclaration;
  readonly axis: SemanticDeclaration;
  readonly sign_convention: SemanticDeclaration;
  readonly sample_time: SemanticDeclaration;
  readonly quality_state: QualityState;
  readonly sample_count: number;
  readonly transformation: CanonicalTransformation;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface CanonicalSourceMapping {
  readonly channel_id: ChannelId;
  readonly source_label: NonEmptyString;
  readonly mapping_state: SemanticState;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
  readonly transformation: CanonicalTransformation;
}

export interface CanonicalTimebase {
  readonly state: SemanticState;
  readonly timestamp_channel_id?: ChannelId;
  readonly timestamp_unit?: Unit;
  readonly sample_interval_seconds?: number;
  readonly sample_rate_hz?: number;
  readonly uniformity?: "UNIFORM" | "IRREGULAR" | "UNKNOWN";
  readonly reason?: ReasonText;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface CanonicalAcquisitionManifest {
  readonly source_observation_id: SourceObservationId;
  readonly source_observation_sha256: Sha256;
  readonly source_artifact_sha256: Sha256;
  readonly canonicalizer_version: string;
  readonly mapping_manifest_id: CanonicalMappingManifestId;
  readonly mapping_manifest_sha256: Sha256;
  readonly adapter_id: NonEmptyString;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface CanonicalIntegrityFinding {
  readonly finding_id: CanonicalIntegrityFindingId;
  readonly code: string;
  readonly severity: "INFO" | "WARNING" | "ERROR";
  readonly message: ReasonText;
  readonly record_index?: number;
  readonly channel_id?: ChannelId;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface CanonicalIntegrityCheck {
  readonly check_id: string;
  readonly status: "PASS" | "WARN" | "FAIL" | "NOT_EVALUATED";
  readonly finding_ids: ReadonlyArray<CanonicalIntegrityFindingId>;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface CanonicalIntegrityReport {
  readonly status: "QUALIFIED" | "REVIEW_REQUIRED" | "REJECTED";
  readonly record_count: number;
  readonly channel_count: number;
  readonly finite_value_count: number;
  readonly finding_count: number;
  readonly findings: ReadonlyArray<CanonicalIntegrityFinding>;
  readonly checks: ReadonlyArray<CanonicalIntegrityCheck>;
}

export interface CanonicalSignalArtifact {
  readonly content_hash: Sha256;
  readonly storage_key: NonEmptyString;
  readonly byte_size: number;
  readonly media_type: string;
  readonly encoding: "MEF_CANONICAL_SIGNAL_NDJSON_V0_1";
  readonly channel_order: ReadonlyArray<ChannelId>;
}

export type ConfigurationResolutionState = "NOT_EVALUATED";

export interface CanonicalizationResult {
  readonly status: "COMPLETE" | "PARTIAL" | "BLOCKED" | "FAILED";
  readonly acquisition: CanonicalAcquisition;
  readonly signal_artifact: CanonicalSignalArtifact;
  readonly integrity_report: CanonicalIntegrityReport;
  readonly mapping_manifest_sha256: Sha256;
  readonly canonical_identity_sha256: Sha256;
}

export interface Actor {
  readonly actor_type: "PRACTITIONER" | "AGENT" | "SYSTEM" | "IMPORT_PROCESS" | "PROCESSOR";
  readonly actor_id: NonEmptyString;
  readonly role: NonEmptyString;
}

export interface PractitionerActor {
  readonly actor_type: "PRACTITIONER";
  readonly actor_id: NonEmptyString;
  readonly role: "QUALIFIED_PRACTITIONER" | "REVIEWER" | "SUPERVISOR";
}

export interface ProcessorReference {
  readonly processor_id: string;
  readonly component_version: string;
}

export interface MetricDefinition {
  readonly definition_id: MetricDefinitionId;
  readonly definition_version: string;
}

export interface Precision {
  readonly representation: "EXACT" | "DECIMAL" | "INTERVAL" | "SIGNIFICANT_DIGITS" | "UNKNOWN";
  readonly digits?: number;
}

export interface NumericValue {
  readonly value: number;
  readonly unit: Unit;
  readonly precision: Precision;
}

export interface TrialOutcome {
  readonly state: "INCLUDED" | "EXCLUDED" | "REVIEW_REQUIRED" | "UNKNOWN" | "UNRESOLVED" | "UNSUPPORTED" | "NOT_APPLICABLE";
  readonly reason_references: ReadonlyArray<ReasonReference>;
}

export interface PractitionerOverride {
  readonly authority_type: "HUMAN_PRACTITIONER";
  readonly actor_id: NonEmptyString;
  readonly attributed_at: Timestamp;
  readonly original_state: NonEmptyString;
  readonly new_state: NonEmptyString;
  readonly reason: ReasonText;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface Disposition {
  readonly state: "PROPOSED_INCLUDE" | "PROPOSED_EXCLUDE" | "REVIEW_REQUIRED" | "FINAL_INCLUDE" | "FINAL_EXCLUDE" | "UNKNOWN" | "UNRESOLVED";
  readonly authority_type: "MACHINE" | "HUMAN_PRACTITIONER";
  readonly reason_references: ReadonlyArray<ReasonReference>;
}

export interface PractitionerDisposition {
  readonly state: "FINAL_INCLUDE" | "FINAL_EXCLUDE" | "REVIEW_REQUIRED";
  readonly authority_type: "HUMAN_PRACTITIONER";
  readonly actor_id: NonEmptyString;
  readonly reason_references: ReadonlyArray<ReasonReference>;
}

export interface Uncertainty {
  readonly state: "KNOWN" | "UNKNOWN" | "UNRESOLVED" | "NOT_APPLICABLE";
  readonly standard_error?: NumericValue;
  readonly lower?: number;
  readonly upper?: number;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface DirectionalProbability {
  readonly state: "KNOWN" | "UNKNOWN" | "UNRESOLVED" | "NOT_APPLICABLE";
  readonly probability?: number;
  readonly direction: "INCREASED" | "DECREASED" | "NO_DIRECTION" | "UNKNOWN";
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface PracticalThresholdInterpretation {
  readonly state: "ELIGIBLE" | "INELIGIBLE" | "UNKNOWN" | "UNRESOLVED" | "NOT_APPLICABLE";
  readonly interpretation?: "ABOVE" | "BELOW" | "WITHIN" | "INDETERMINATE" | "NOT_REGISTERED" | "NOT_APPLICABLE";
  readonly threshold_reference?: NonEmptyString;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface Diagnostic {
  readonly code: "INSUFFICIENT_EVIDENCE" | "REFERENCE_NOT_MATURE" | "MEASUREMENT_INELIGIBLE" | "UNCERTAINTY_UNRESOLVED" | "CONFLICTING_METADATA" | "LIMITATION_PRESENT";
  readonly description: ReasonText;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface Limitation {
  readonly code: "MISSING_ACQUISITION_SEMANTICS" | "MISSING_PROTOCOL_EVIDENCE" | "REFERENCE_IMMATURITY" | "UNCERTAINTY" | "PROCESSOR_LIMITATION" | "SCOPE_LIMITATION";
  readonly description: ReasonText;
}

export interface Integrity {
  readonly algorithm: "SHA-256";
  readonly digest: Sha256;
  readonly integrity_state: "DECLARED" | "VERIFIED" | "FAILED" | "UNKNOWN";
  readonly component_version: string;
  readonly signed: boolean;
  readonly verification_evidence_references?: ReadonlyArray<EvidenceReference>;
}

export type ObjectReference = { readonly entity_type: "SourceArtifact"; readonly object_id: SourceArtifactId } | { readonly entity_type: "ImportAttempt"; readonly object_id: ImportAttemptId } | { readonly entity_type: "CanonicalAcquisition"; readonly object_id: CanonicalAcquisitionId } | { readonly entity_type: "ConfigurationContract"; readonly object_id: ConfigurationContractId } | { readonly entity_type: "ProtocolContract"; readonly object_id: ProtocolContractId } | { readonly entity_type: "Trial"; readonly object_id: TrialId } | { readonly entity_type: "Session"; readonly object_id: SessionId } | { readonly entity_type: "MetricObservation"; readonly object_id: MetricObservationId } | { readonly entity_type: "ReferenceEpoch"; readonly object_id: ReferenceEpochId } | { readonly entity_type: "InferenceResult"; readonly object_id: InferenceResultId } | { readonly entity_type: "EvidenceManifest"; readonly object_id: EvidenceManifestId } | { readonly entity_type: "PractitionerDecision"; readonly object_id: PractitionerDecisionId } | { readonly entity_type: "AgentContext"; readonly object_id: AgentContextId } | { readonly entity_type: "AuditEvent"; readonly object_id: AuditEventId } | { readonly entity_type: "Command"; readonly object_id: CommandId } | { readonly entity_type: "Job"; readonly object_id: JobId } | { readonly entity_type: "JobAttempt"; readonly object_id: JobAttemptId } | { readonly entity_type: "ProgressEvent"; readonly object_id: ProgressEventId };

export interface Membership {
  readonly session_ids: ReadonlyArray<SessionId>;
  readonly metric_observation_ids: ReadonlyArray<MetricObservationId>;
  readonly membership_digest: Sha256;
}

export interface ContextScope {
  readonly workspace: ScopeSlot;
  readonly athlete: ScopeSlot;
  readonly measurement_case: ScopeSlot;
}

export interface ScopeSlot {
  readonly state: SemanticState;
  readonly value?: NonEmptyString;
  readonly reason?: ReasonText;
}

export interface MachineRecommendation {
  readonly source: "SYSTEM_PROCESSOR" | "AGENT_DRAFT";
  readonly recommendation: "ACCEPT" | "REJECT" | "REVIEW_REQUIRED";
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export type SourceArtifactLifecycleState = "REGISTERED" | "VERIFIED" | "INVALID";

export type ImportAttemptState = "RECEIVED" | "VALIDATING" | "ACCEPTED" | "REJECTED" | "UNSUPPORTED" | "FAILED";

export type AcquisitionState = "DECLARED" | "PARTIALLY_RESOLVED" | "QUALIFIED" | "UNQUALIFIED" | "REJECTED" | "UNKNOWN";

export type ConfigurationState = "RESOLVED_QUALIFIED" | "RESOLVED_UNQUALIFIED" | "PARTIALLY_RESOLVED" | "CONFLICTING_METADATA" | "UNRESOLVED";

export type ProtocolState = "DECLARED" | "ELIGIBLE" | "INELIGIBLE" | "UNRESOLVED" | "REVIEW_REQUIRED";

export type TrialState = "DECLARED" | "PENDING_REVIEW" | "ELIGIBLE" | "INELIGIBLE" | "REJECTED" | "PRACTITIONER_OVERRIDDEN";

export type SessionState = "DRAFT" | "MACHINE_PROPOSED" | "REVIEW_REQUIRED" | "HUMAN_FINAL" | "REJECTED" | "PRACTITIONER_OVERRIDDEN";

export type ObservationState = "OBSERVED" | "UNRESOLVED" | "INELIGIBLE" | "UNSUPPORTED";

export type EpochMaturityState = "IMMATURE" | "MATURE" | "UNKNOWN" | "UNRESOLVED";

export type EpochApprovalState = "NOT_REQUESTED" | "PENDING" | "APPROVED" | "REJECTED" | "UNKNOWN";

export type InferenceState = "PRODUCED" | "INELIGIBLE" | "UNRESOLVED" | "FAILED" | "REVIEW_REQUIRED";

export type ManifestState = "DECLARED" | "INTEGRITY_VERIFIED" | "INTEGRITY_FAILED" | "SCOPE_INCOMPLETE" | "REVIEW_REQUIRED";

export type DecisionState = "DRAFT" | "RECORDED" | "REVIEW_REQUIRED" | "SUPERSEDES_PRIOR";

export type DecisionValue = "ACCEPT" | "REJECT" | "REVIEW_REQUIRED" | "OVERRIDE" | "ACKNOWLEDGE" | "NOT_APPLICABLE";

export type ContextState = "BOUNDED" | "PARTIALLY_BOUNDED" | "UNKNOWN" | "UNRESOLVED";

export type AuditAction = "CREATED" | "VALIDATED" | "STATE_CHANGED" | "OVERRIDDEN" | "APPROVED" | "REJECTED" | "LINKED" | "UNLINKED" | "COMMAND_ACCEPTED" | "COMMAND_IDEMPOTENT_REUSED" | "JOB_CLAIMED" | "ATTEMPT_STARTED" | "PROGRESS_RECORDED" | "RETRY_SCHEDULED" | "CANCELLATION_REQUESTED" | "CANCELLATION_ACKNOWLEDGED" | "ATTEMPT_COMPLETED" | "JOB_SUCCEEDED" | "JOB_FAILED" | "JOB_CANCELED" | "UNKNOWN_OUTCOME" | "RECONCILIATION_ACTION";

export type CommandType = "FIXTURE_EXECUTION" | "IMPORT" | "SCIENTIFIC_PROCESSING" | "INFERENCE" | "EVIDENCE_ASSEMBLY" | "AUTHORIZED_ACTION";

export type RequestedOperation = "EXECUTE";

export type FixtureScenario = "SUCCESS" | "RETRY_THEN_SUCCESS" | "NON_RETRYABLE_FAILURE" | "CANCELLABLE" | "UNKNOWN_OUTCOME" | "PROGRESS";

export type FailureCategory = "RETRYABLE" | "NON_RETRYABLE" | "UNKNOWN_OUTCOME";

export type RetryDecision = "NOT_APPLICABLE" | "RETRY_SCHEDULED" | "RETRY_EXHAUSTED" | "MANUAL_RECONCILIATION_REQUIRED" | "CANCELED";

export type JobState = "QUEUED" | "RUNNING" | "RETRY_WAIT" | "CANCEL_REQUESTED" | "SUCCEEDED" | "FAILED" | "CANCELED" | "UNKNOWN_OUTCOME";

export type JobAttemptOutcome = "STARTED" | "SUCCEEDED" | "FAILED_RETRYABLE" | "FAILED_NON_RETRYABLE" | "UNKNOWN_OUTCOME" | "CANCELED";

export type WorkerType = "FIXTURE";

export type ProgressPhase = "QUEUED" | "STARTING" | "RUNNING" | "RETRYING" | "CANCELLATION_REQUESTED" | "CANCELLATION_ACKNOWLEDGED" | "COMPLETED" | "RECONCILING";

export type ProgressCode = "COMMAND_ACCEPTED" | "ATTEMPT_STARTED" | "STEP_COMPLETED" | "RETRY_SCHEDULED" | "CANCELLATION_REQUESTED" | "CANCELLATION_ACKNOWLEDGED" | "ATTEMPT_COMPLETED" | "JOB_COMPLETED" | "OUTCOME_UNKNOWN" | "RECONCILIATION_REQUIRED";

export type ExecutionErrorCode = "IDEMPOTENCY_CONFLICT" | "JOB_NOT_FOUND" | "JOB_NOT_CLAIMABLE" | "INVALID_JOB_TRANSITION" | "JOB_ALREADY_TERMINAL" | "CANCELLATION_NOT_ALLOWED" | "ATTEMPT_LIMIT_EXCEEDED" | "WORKER_FAILURE_RETRYABLE" | "WORKER_FAILURE_NON_RETRYABLE" | "EXECUTION_OUTCOME_UNKNOWN" | "JOB_PERSISTENCE_FAILED" | "UNKNOWN_COMMAND_TYPE" | "UNKNOWN_WORKER_TYPE" | "PROGRESS_SEQUENCE_CONFLICT" | "RECONCILIATION_REQUIRED" | "INVALID_COMMAND_PAYLOAD" | "INVALID_PROGRESS_EVENT";

export type ReconciliationState = "NONE" | "RECONCILIATION_REQUIRED" | "RECONCILED";

export interface CommandPayload {
  readonly payload_kind: "STRUCTURAL";
  readonly input_label: NonEmptyString;
  readonly input_value: ReasonText;
  readonly fixture_scenario?: FixtureScenario;
}

export interface CorrelationMetadata {
  readonly correlation_id: NonEmptyString;
  readonly request_id: NonEmptyString;
  readonly causation_id?: NonEmptyString;
}

export interface RetryPolicy {
  readonly max_attempts: number;
  readonly backoff_milliseconds: number;
  readonly backoff_strategy: "FIXED";
}

export interface JobResult {
  readonly result_code: "COMPLETED" | "CANCELED";
  readonly summary_code: NonEmptyString;
  readonly result_reference?: ObjectReference;
}

export interface ExecutionError {
  readonly code: ExecutionErrorCode;
  readonly category: FailureCategory;
}

export interface JobCancellation {
  readonly requested_at: Timestamp;
  readonly acknowledged_at?: Timestamp;
  readonly canceled_at?: Timestamp;
  readonly reason_code: "USER_REQUESTED" | "SAFE_BOUNDARY";
}

export interface SourceArtifact {
  readonly entity_type: "SourceArtifact";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/source-artifact.schema.json";
  readonly schema_version: SchemaVersion;
  readonly source_artifact_id: SourceArtifactId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly lifecycle_state: SourceArtifactLifecycleState;
  readonly content_hash: Sha256;
  readonly byte_size: number;
  readonly media_type: string;
  readonly original_filename: NonEmptyString;
  readonly ingested_at: Timestamp;
  readonly source_declaration: SemanticDeclaration;
  readonly immutable_source: true;
}

export interface ImportAttempt {
  readonly entity_type: "ImportAttempt";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/import-attempt.schema.json";
  readonly schema_version: SchemaVersion;
  readonly import_attempt_id: ImportAttemptId;
  readonly record_version: number;
  readonly source_artifact_id: SourceArtifactId;
  readonly attempt_number: number;
  readonly attempted_at: Timestamp;
  readonly attempt_state: ImportAttemptState;
  readonly errors: ReadonlyArray<ContractError>;
}

export interface CanonicalAcquisition {
  readonly entity_type: "CanonicalAcquisition";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/canonical-acquisition.schema.json";
  readonly schema_version: SchemaVersion;
  readonly canonical_acquisition_id: CanonicalAcquisitionId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly source_artifact_id: SourceArtifactId;
  readonly source_observation_id: SourceObservationId;
  readonly source_observation_sha256: Sha256;
  readonly canonicalizer_version: string;
  readonly mapping_manifest_sha256: Sha256;
  readonly signal_artifact_sha256: Sha256;
  readonly integrity_report_sha256: Sha256;
  readonly canonical_identity_sha256: Sha256;
  readonly acquisition_state: AcquisitionState;
  readonly modality: SemanticDeclaration;
  readonly channels: ReadonlyArray<CanonicalChannel>;
  readonly source_mappings: ReadonlyArray<CanonicalSourceMapping>;
  readonly sample_semantics: SemanticDeclaration;
  readonly timebase: CanonicalTimebase;
  readonly synchronization: SemanticDeclaration;
  readonly calibration: SemanticDeclaration;
  readonly preprocessing: SemanticDeclaration;
  readonly missingness_quality: SemanticDeclaration;
  readonly configuration_resolution: ConfigurationResolutionState;
  readonly manifest: CanonicalAcquisitionManifest;
  readonly signal_artifact: CanonicalSignalArtifact;
  readonly integrity_report: CanonicalIntegrityReport;
  readonly quality_state: QualityState;
  readonly blocking_reasons: ReadonlyArray<ReasonReference>;
}

export interface AcquisitionConfigurationContract {
  readonly contract: "single.total_fz" | "dual.independent_fz" | "UNKNOWN" | "UNSUPPORTED";
  readonly state: "RESOLVED" | "UNKNOWN" | "UNSUPPORTED" | "CONFLICTING";
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
}

export interface ChannelCapability {
  readonly channel_id: ChannelId;
  readonly physical_quantity: SemanticDeclaration;
  readonly axis: SemanticDeclaration;
  readonly sign: SemanticDeclaration;
  readonly plate_identity: SemanticDeclaration;
  readonly sample_count: number;
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
}

export interface SampleRateResolution {
  readonly state: "RESOLVED" | "UNKNOWN" | "CONFLICTING";
  readonly sample_rate_hz?: number;
  readonly interval_seconds?: number;
  readonly source: "EXPLICIT_SOURCE_DECLARATION" | "CANONICAL_TIMEBASE" | "EXACT_TIMESTAMP_INTERVAL" | "UNKNOWN";
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
}

export interface SynchronizationResolution {
  readonly state: "SYNCHRONIZED" | "UNSYNCHRONIZED" | "UNKNOWN" | "CONFLICTING" | "NOT_APPLICABLE";
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
}

export interface AxisSignResolution {
  readonly state: "RESOLVED" | "UNKNOWN" | "CONFLICTING";
  readonly axis?: NonEmptyString;
  readonly sign?: NonEmptyString;
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
}

export interface PreprocessingResolution {
  readonly state: "NONE_DECLARED" | "DECLARED" | "UNKNOWN" | "CONFLICTING";
  readonly description?: ReasonText;
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
}

export interface CalibrationResolution {
  readonly state: "CONFIRMED" | "DECLARED" | "UNKNOWN" | "CONFLICTING" | "NOT_APPLICABLE";
  readonly description?: ReasonText;
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
}

export interface ZeroingResolution {
  readonly state: "CONFIRMED" | "DECLARED" | "UNKNOWN" | "CONFLICTING" | "NOT_APPLICABLE";
  readonly description?: ReasonText;
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
}

export interface ProtocolEligibilityResolution {
  readonly state: "ELIGIBLE" | "INELIGIBLE" | "UNRESOLVED" | "NOT_EVALUATED";
  readonly authority_version: NonEmptyString;
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
}

export interface ConfigurationFinding {
  readonly code: string;
  readonly severity: "INFO" | "WARNING" | "ERROR";
  readonly message: ReasonText;
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
}

export interface ConfigurationEvidenceReference {
  readonly source_artifact_id: SourceArtifactId;
  readonly source_observation_id: SourceObservationId;
  readonly canonical_acquisition_id: CanonicalAcquisitionId;
  readonly channel_id?: ChannelId;
  readonly locator: NonEmptyString;
  readonly content_hash: Sha256;
}

export interface AcquisitionConfigurationResolution {
  readonly resolver_version: string;
  readonly authority_version: NonEmptyString;
  readonly source_artifact_id: SourceArtifactId;
  readonly source_observation_id: SourceObservationId;
  readonly canonical_acquisition_id: CanonicalAcquisitionId;
  readonly canonical_identity_sha256: Sha256;
  readonly evidence_manifest_sha256?: Sha256;
  readonly configuration_state: ConfigurationState;
  readonly physical_contract: AcquisitionConfigurationContract;
  readonly channel_capabilities: ReadonlyArray<ChannelCapability>;
  readonly sample_rate: SampleRateResolution;
  readonly synchronization: SynchronizationResolution;
  readonly axis_sign: AxisSignResolution;
  readonly preprocessing: PreprocessingResolution;
  readonly calibration: CalibrationResolution;
  readonly zeroing: ZeroingResolution;
  readonly protocol_eligibility: ProtocolEligibilityResolution;
  readonly findings: ReadonlyArray<ConfigurationFinding>;
  readonly evidence_references: ReadonlyArray<ConfigurationEvidenceReference>;
  readonly resolution_sha256: Sha256;
}

export interface ConfigurationContract {
  readonly entity_type: "ConfigurationContract";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/configuration-contract.schema.json";
  readonly schema_version: SchemaVersion;
  readonly configuration_contract_id: ConfigurationContractId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly canonical_acquisition_id: CanonicalAcquisitionId;
  readonly configuration_state: ConfigurationState;
  readonly configuration_name: SemanticDeclaration;
  readonly qualification_evidence_references: ReadonlyArray<EvidenceReference>;
  readonly reason_references: ReadonlyArray<ReasonReference>;
  readonly resolution?: AcquisitionConfigurationResolution;
}

export interface ProtocolContract {
  readonly entity_type: "ProtocolContract";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/protocol-contract.schema.json";
  readonly schema_version: SchemaVersion;
  readonly protocol_contract_id: ProtocolContractId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly protocol_key: "bilateral-unloaded-hands-on-hips-countermovement-jump";
  readonly protocol_version: string;
  readonly protocol_state: ProtocolState;
  readonly bilateral: ConditionObservation;
  readonly unloaded: ConditionObservation;
  readonly hands_on_hips: ConditionObservation;
  readonly countermovement_jump: ConditionObservation;
  readonly eligibility_evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface Trial {
  readonly entity_type: "Trial";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/trial.schema.json";
  readonly schema_version: SchemaVersion;
  readonly trial_id: TrialId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly trial_state: TrialState;
  readonly canonical_acquisition_id: CanonicalAcquisitionId;
  readonly protocol_contract_id: ProtocolContractId;
  readonly session_id?: SessionId;
  readonly quality_state: QualityState;
  readonly original_outcome: TrialOutcome;
  readonly practitioner_override?: PractitionerOverride;
  readonly event_evidence_references: ReadonlyArray<EvidenceReference>;
  readonly eligibility_evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface Session {
  readonly entity_type: "Session";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/session.schema.json";
  readonly schema_version: SchemaVersion;
  readonly session_id: SessionId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly session_state: SessionState;
  readonly contributing_trial_ids: ReadonlyArray<TrialId>;
  readonly machine_proposed_disposition: Disposition;
  readonly human_final_disposition?: PractitionerDisposition;
  readonly review_references: ReadonlyArray<EvidenceReference>;
}

export interface MetricObservation {
  readonly entity_type: "MetricObservation";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/metric-observation.schema.json";
  readonly schema_version: SchemaVersion;
  readonly metric_observation_id: MetricObservationId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly metric_definition: MetricDefinition;
  readonly value: NumericValue;
  readonly processor: ProcessorReference;
  readonly contributing_trial_ids: ReadonlyArray<TrialId>;
  readonly contributing_session_id?: SessionId;
  readonly observation_state: ObservationState;
  readonly eligibility_state: QualityState;
  readonly evidence_references: ReadonlyArray<EvidenceReference>;
}

export interface ReferenceEpoch {
  readonly entity_type: "ReferenceEpoch";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/reference-epoch.schema.json";
  readonly schema_version: SchemaVersion;
  readonly reference_epoch_id: ReferenceEpochId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly reference_policy_id: string;
  readonly reference_policy_version: string;
  readonly membership: Membership;
  readonly maturity_state: EpochMaturityState;
  readonly approval_state: EpochApprovalState;
  readonly membership_evidence_references: ReadonlyArray<EvidenceReference>;
  readonly approval_decision_id?: PractitionerDecisionId;
  readonly approval_evidence_references?: ReadonlyArray<EvidenceReference>;
}

export interface InferenceResult {
  readonly entity_type: "InferenceResult";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/inference-result.schema.json";
  readonly schema_version: SchemaVersion;
  readonly inference_result_id: InferenceResultId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly metric_observation_id: MetricObservationId;
  readonly reference_epoch_id: ReferenceEpochId;
  readonly inference_state: InferenceState;
  readonly measurement_estimate: NumericValue;
  readonly uncertainty: Uncertainty;
  readonly directional_probability: DirectionalProbability;
  readonly practical_threshold_interpretation: PracticalThresholdInterpretation;
  readonly diagnostics: ReadonlyArray<Diagnostic>;
  readonly eligibility_state: QualityState;
  readonly limitations: ReadonlyArray<Limitation>;
}

export interface EvidenceManifest {
  readonly entity_type: "EvidenceManifest";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/evidence-manifest.schema.json";
  readonly schema_version: SchemaVersion;
  readonly evidence_manifest_id: EvidenceManifestId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly manifest_version: string;
  readonly manifest_state: ManifestState;
  readonly source_artifact_ids: ReadonlyArray<SourceArtifactId>;
  readonly configuration_contract_ids: ReadonlyArray<ConfigurationContractId>;
  readonly protocol_contract_ids: ReadonlyArray<ProtocolContractId>;
  readonly processors: ReadonlyArray<ProcessorReference>;
  readonly metric_observation_ids: ReadonlyArray<MetricObservationId>;
  readonly session_ids: ReadonlyArray<SessionId>;
  readonly reference_epoch_ids: ReadonlyArray<ReferenceEpochId>;
  readonly inference_result_ids: ReadonlyArray<InferenceResultId>;
  readonly practitioner_decision_ids: ReadonlyArray<PractitionerDecisionId>;
  readonly integrity: Integrity;
  readonly component_version: string;
}

export interface PractitionerDecision {
  readonly entity_type: "PractitionerDecision";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/practitioner-decision.schema.json";
  readonly schema_version: SchemaVersion;
  readonly practitioner_decision_id: PractitionerDecisionId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly decision_state: DecisionState;
  readonly authority_type: "HUMAN_PRACTITIONER";
  readonly actor: PractitionerActor;
  readonly decided_at: Timestamp;
  readonly decision: DecisionValue;
  readonly rationale: ReasonText;
  readonly target: ObjectReference;
  readonly evidence_manifest_ids: ReadonlyArray<EvidenceManifestId>;
  readonly machine_recommendation?: MachineRecommendation;
}

export interface AgentContext {
  readonly entity_type: "AgentContext";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/agent-context.schema.json";
  readonly schema_version: SchemaVersion;
  readonly agent_context_id: AgentContextId;
  readonly record_version: number;
  readonly created_at: Timestamp;
  readonly context_state: ContextState;
  readonly scope: ContextScope;
  readonly screen_object_context: ScopeSlot;
  readonly selected_evidence_manifest_ids: ReadonlyArray<EvidenceManifestId>;
  readonly unresolved_warnings: ReadonlyArray<ReasonText>;
}

export interface Command {
  readonly entity_type: "Command";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/command.schema.json";
  readonly schema_version: SchemaVersion;
  readonly command_id: CommandId;
  readonly record_version: number;
  readonly command_type: CommandType;
  readonly idempotency_key: IdempotencyKey;
  readonly semantic_input_digest: Sha256;
  readonly submitted_at: Timestamp;
  readonly request_payload: CommandPayload;
  readonly requested_operation: RequestedOperation;
  readonly request_reference?: ObjectReference;
  readonly authority_context_reference: ObjectReference;
  readonly correlation_metadata: CorrelationMetadata;
}

export interface Job {
  readonly entity_type: "Job";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/job.schema.json";
  readonly schema_version: SchemaVersion;
  readonly job_id: JobId;
  readonly record_version: number;
  readonly command_id: CommandId;
  readonly created_at: Timestamp;
  readonly queued_at: Timestamp;
  readonly started_at?: Timestamp;
  readonly updated_at: Timestamp;
  readonly finished_at?: Timestamp;
  readonly state: JobState;
  readonly retry_policy: RetryPolicy;
  readonly current_attempt_number: number;
  readonly next_eligible_attempt_at?: Timestamp;
  readonly last_attempt_id?: JobAttemptId;
  readonly cancellation?: JobCancellation;
  readonly reconciliation_state: ReconciliationState;
  readonly result?: JobResult;
  readonly error?: ExecutionError;
}

export interface JobAttempt {
  readonly entity_type: "JobAttempt";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/job-attempt.schema.json";
  readonly schema_version: SchemaVersion;
  readonly job_attempt_id: JobAttemptId;
  readonly record_version: number;
  readonly job_id: JobId;
  readonly attempt_number: number;
  readonly worker_identity: string;
  readonly worker_type: WorkerType;
  readonly claimed_at: Timestamp;
  readonly started_at?: Timestamp;
  readonly ended_at?: Timestamp;
  readonly lease_expires_at?: Timestamp;
  readonly outcome: JobAttemptOutcome;
  readonly failure_category?: FailureCategory;
  readonly retry_decision: RetryDecision;
  readonly cancellation_acknowledged_at?: Timestamp;
  readonly result?: JobResult;
  readonly error?: ExecutionError;
}

export interface ProgressEvent {
  readonly entity_type: "ProgressEvent";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/progress-event.schema.json";
  readonly schema_version: SchemaVersion;
  readonly progress_event_id: ProgressEventId;
  readonly record_version: number;
  readonly job_id: JobId;
  readonly job_attempt_id?: JobAttemptId;
  readonly sequence: number;
  readonly occurred_at: Timestamp;
  readonly phase: ProgressPhase;
  readonly message_code: ProgressCode;
  readonly progress_value?: number;
}

export interface AuditEvent {
  readonly entity_type: "AuditEvent";
  readonly schema_id: "https://schemas.sportsagentslab.local/mef/1.0.0/audit-event.schema.json";
  readonly schema_version: SchemaVersion;
  readonly audit_event_id: AuditEventId;
  readonly record_version: number;
  readonly occurred_at: Timestamp;
  readonly actor: Actor;
  readonly audit_action: AuditAction;
  readonly object: ObjectReference;
  readonly authority_type: "SYSTEM" | "MACHINE" | "HUMAN_PRACTITIONER" | "AGENT_DRAFT";
  readonly reason: ReasonText;
  readonly prior_reference?: ObjectReference;
  readonly new_reference?: ObjectReference;
  readonly immutable_history: true;
}

export type EntityRecord = SourceArtifact | ImportAttempt | CanonicalAcquisition | ConfigurationContract | ProtocolContract | Trial | Session | MetricObservation | ReferenceEpoch | InferenceResult | EvidenceManifest | PractitionerDecision | AgentContext | AuditEvent | Command | Job | JobAttempt | ProgressEvent;
