"""Generated by scripts/generate_models.py. Do not edit manually."""

# fmt: off

from __future__ import annotations

import re
from enum import Enum
from typing import Literal, NotRequired, TypeAlias, TypedDict

SchemaVersion: TypeAlias = Literal['1.0.0']

Timestamp: TypeAlias = str

NonEmptyString: TypeAlias = str

ReasonText: TypeAlias = str

class SourceArtifactId(str):
    _pattern = re.compile('^src_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> SourceArtifactId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('SourceArtifactId' + ' has an invalid value')
        return str.__new__(cls, value)

class ImportAttemptId(str):
    _pattern = re.compile('^imp_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> ImportAttemptId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('ImportAttemptId' + ' has an invalid value')
        return str.__new__(cls, value)

class CanonicalAcquisitionId(str):
    _pattern = re.compile('^acq_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> CanonicalAcquisitionId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('CanonicalAcquisitionId' + ' has an invalid value')
        return str.__new__(cls, value)

class ConfigurationContractId(str):
    _pattern = re.compile('^cfg_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> ConfigurationContractId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('ConfigurationContractId' + ' has an invalid value')
        return str.__new__(cls, value)

class ProtocolContractId(str):
    _pattern = re.compile('^pro_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> ProtocolContractId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('ProtocolContractId' + ' has an invalid value')
        return str.__new__(cls, value)

class TrialId(str):
    _pattern = re.compile('^trl_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> TrialId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('TrialId' + ' has an invalid value')
        return str.__new__(cls, value)

class SessionId(str):
    _pattern = re.compile('^ses_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> SessionId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('SessionId' + ' has an invalid value')
        return str.__new__(cls, value)

class MetricObservationId(str):
    _pattern = re.compile('^met_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> MetricObservationId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('MetricObservationId' + ' has an invalid value')
        return str.__new__(cls, value)

class ReferenceEpochId(str):
    _pattern = re.compile('^epoch_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> ReferenceEpochId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('ReferenceEpochId' + ' has an invalid value')
        return str.__new__(cls, value)

class InferenceResultId(str):
    _pattern = re.compile('^inf_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> InferenceResultId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('InferenceResultId' + ' has an invalid value')
        return str.__new__(cls, value)

class EvidenceManifestId(str):
    _pattern = re.compile('^evm_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> EvidenceManifestId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('EvidenceManifestId' + ' has an invalid value')
        return str.__new__(cls, value)

class PractitionerDecisionId(str):
    _pattern = re.compile('^dec_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> PractitionerDecisionId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('PractitionerDecisionId' + ' has an invalid value')
        return str.__new__(cls, value)

class AgentContextId(str):
    _pattern = re.compile('^ctx_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> AgentContextId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('AgentContextId' + ' has an invalid value')
        return str.__new__(cls, value)

class AuditEventId(str):
    _pattern = re.compile('^aud_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> AuditEventId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('AuditEventId' + ' has an invalid value')
        return str.__new__(cls, value)

class CommandId(str):
    _pattern = re.compile('^cmd_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> CommandId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('CommandId' + ' has an invalid value')
        return str.__new__(cls, value)

class JobId(str):
    _pattern = re.compile('^job_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> JobId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('JobId' + ' has an invalid value')
        return str.__new__(cls, value)

class JobAttemptId(str):
    _pattern = re.compile('^jatt_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> JobAttemptId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('JobAttemptId' + ' has an invalid value')
        return str.__new__(cls, value)

class ProgressEventId(str):
    _pattern = re.compile('^pev_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> ProgressEventId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('ProgressEventId' + ' has an invalid value')
        return str.__new__(cls, value)

IdempotencyKey: TypeAlias = str

MetricDefinitionId: TypeAlias = str

ChannelId: TypeAlias = str

class SourceObservationId(str):
    _pattern = re.compile('^sob_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> SourceObservationId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('SourceObservationId' + ' has an invalid value')
        return str.__new__(cls, value)

class CanonicalMappingManifestId(str):
    _pattern = re.compile('^map_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> CanonicalMappingManifestId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('CanonicalMappingManifestId' + ' has an invalid value')
        return str.__new__(cls, value)

class CanonicalIntegrityFindingId(str):
    _pattern = re.compile('^cif_[a-z0-9][a-z0-9_-]{0,127}$')

    def __new__(cls, value: str) -> CanonicalIntegrityFindingId:
        if not isinstance(value, str) or cls._pattern.fullmatch(value) is None:
            raise ValueError('CanonicalIntegrityFindingId' + ' has an invalid value')
        return str.__new__(cls, value)

Sha256: TypeAlias = str

class SemanticState(str, Enum):
    KNOWN = 'KNOWN'
    UNKNOWN = 'UNKNOWN'
    UNRESOLVED = 'UNRESOLVED'
    UNSUPPORTED = 'UNSUPPORTED'
    NOT_APPLICABLE = 'NOT_APPLICABLE'
    ABSENT = 'ABSENT'

class QualityState(str, Enum):
    QUALIFIED = 'QUALIFIED'
    UNQUALIFIED = 'UNQUALIFIED'
    UNKNOWN = 'UNKNOWN'
    UNRESOLVED = 'UNRESOLVED'
    UNSUPPORTED = 'UNSUPPORTED'
    NOT_APPLICABLE = 'NOT_APPLICABLE'
    REJECTED = 'REJECTED'
    REVIEW_REQUIRED = 'REVIEW_REQUIRED'

class EntityType(str, Enum):
    SOURCEARTIFACT = 'SourceArtifact'
    IMPORTATTEMPT = 'ImportAttempt'
    CANONICALACQUISITION = 'CanonicalAcquisition'
    CONFIGURATIONCONTRACT = 'ConfigurationContract'
    PROTOCOLCONTRACT = 'ProtocolContract'
    TRIAL = 'Trial'
    SESSION = 'Session'
    METRICOBSERVATION = 'MetricObservation'
    REFERENCEEPOCH = 'ReferenceEpoch'
    INFERENCERESULT = 'InferenceResult'
    EVIDENCEMANIFEST = 'EvidenceManifest'
    PRACTITIONERDECISION = 'PractitionerDecision'
    AGENTCONTEXT = 'AgentContext'
    AUDITEVENT = 'AuditEvent'
    COMMAND = 'Command'
    JOB = 'Job'
    JOBATTEMPT = 'JobAttempt'
    PROGRESSEVENT = 'ProgressEvent'

class ErrorCode(str, Enum):
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    UNKNOWN_ENTITY_TYPE = 'UNKNOWN_ENTITY_TYPE'
    UNKNOWN_ENUM_VALUE = 'UNKNOWN_ENUM_VALUE'
    UNSUPPORTED_SCHEMA_VERSION = 'UNSUPPORTED_SCHEMA_VERSION'
    UNKNOWN_SCHEMA_VERSION = 'UNKNOWN_SCHEMA_VERSION'
    MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD'
    INVALID_IDENTIFIER = 'INVALID_IDENTIFIER'
    INVALID_TIMESTAMP = 'INVALID_TIMESTAMP'
    INVALID_HASH = 'INVALID_HASH'
    INVALID_STATE_TRANSITION_INPUT = 'INVALID_STATE_TRANSITION_INPUT'
    UNRESOLVED_REFERENCE = 'UNRESOLVED_REFERENCE'
    CONFLICTING_METADATA = 'CONFLICTING_METADATA'
    UNSUPPORTED_CONFIGURATION = 'UNSUPPORTED_CONFIGURATION'
    INCOMPATIBLE_CONTRACT_VERSION = 'INCOMPATIBLE_CONTRACT_VERSION'
    UNKNOWN_GOVERNED_FIELD = 'UNKNOWN_GOVERNED_FIELD'
    INVALID_EVIDENCE_REFERENCE = 'INVALID_EVIDENCE_REFERENCE'
    INVALID_UNIT = 'INVALID_UNIT'
    INVALID_TYPE = 'INVALID_TYPE'
    FORBIDDEN_FIELD = 'FORBIDDEN_FIELD'
    FORBIDDEN_AUTHORITY_COMBINATION = 'FORBIDDEN_AUTHORITY_COMBINATION'

class ContractError(TypedDict):
    taxonomy_version: SchemaVersion
    code: ErrorCode
    message: ReasonText
    path: str

class EvidenceReference(TypedDict):
    evidence_manifest_id: EvidenceManifestId
    component: NonEmptyString
    locator: NonEmptyString
    content_hash: NotRequired[Sha256]

class ReasonReference(TypedDict):
    code: str
    description: ReasonText
    evidence_references: list[EvidenceReference]

class SemanticDeclaration(TypedDict):
    state: SemanticState
    value: NotRequired[NonEmptyString]
    reason: NotRequired[ReasonText]
    evidence_references: list[EvidenceReference]

class Unit(TypedDict):
    system: Literal['SI', 'NATIVE']
    symbol: str

class UnitDeclaration(TypedDict):
    state: SemanticState
    unit: NotRequired[Unit]
    reason: NotRequired[ReasonText]
    evidence_references: list[EvidenceReference]

class ConditionObservation(TypedDict):
    condition: Literal['BILATERAL', 'UNLOADED', 'HANDS_ON_HIPS', 'COUNTERMOVEMENT_JUMP']
    observation_state: Literal['CONFIRMED', 'NOT_CONFIRMED', 'UNKNOWN', 'UNRESOLVED', 'UNSUPPORTED', 'NOT_APPLICABLE']
    authority_type: Literal['HUMAN_PRACTITIONER', 'MACHINE_OBSERVED']
    evidence_references: list[EvidenceReference]

class Channel(TypedDict):
    channel_id: ChannelId
    physical_quantity: SemanticDeclaration
    unit: UnitDeclaration
    axis: SemanticDeclaration
    sign_convention: SemanticDeclaration
    sample_time: SemanticDeclaration
    quality_state: QualityState

class SourceMapping(TypedDict):
    channel_id: ChannelId
    source_label: NonEmptyString
    mapping_state: SemanticState
    evidence_references: list[EvidenceReference]

class CanonicalTransformation(TypedDict):
    kind: Literal['IDENTITY', 'UNIT_CONVERSION', 'SIGN_FLIP', 'LINEAR_SCALE']
    scale: float
    offset: float
    source_unit: NotRequired[Unit]
    target_unit: NotRequired[Unit]
    source_axis: NotRequired[NonEmptyString]
    target_axis: NotRequired[NonEmptyString]

class CanonicalChannel(TypedDict):
    channel_id: ChannelId
    physical_quantity: SemanticDeclaration
    unit: UnitDeclaration
    axis: SemanticDeclaration
    sign_convention: SemanticDeclaration
    sample_time: SemanticDeclaration
    quality_state: QualityState
    sample_count: int
    transformation: CanonicalTransformation
    evidence_references: list[EvidenceReference]

class CanonicalSourceMapping(TypedDict):
    channel_id: ChannelId
    source_label: NonEmptyString
    mapping_state: SemanticState
    evidence_references: list[EvidenceReference]
    transformation: CanonicalTransformation

class CanonicalTimebase(TypedDict):
    state: SemanticState
    timestamp_channel_id: NotRequired[ChannelId]
    timestamp_unit: NotRequired[Unit]
    sample_interval_seconds: NotRequired[float]
    sample_rate_hz: NotRequired[float]
    uniformity: NotRequired[Literal['UNIFORM', 'IRREGULAR', 'UNKNOWN']]
    reason: NotRequired[ReasonText]
    evidence_references: list[EvidenceReference]

class CanonicalAcquisitionManifest(TypedDict):
    source_observation_id: SourceObservationId
    source_observation_sha256: Sha256
    source_artifact_sha256: Sha256
    canonicalizer_version: str
    mapping_manifest_id: CanonicalMappingManifestId
    mapping_manifest_sha256: Sha256
    adapter_id: NonEmptyString
    evidence_references: list[EvidenceReference]

class CanonicalIntegrityFinding(TypedDict):
    finding_id: CanonicalIntegrityFindingId
    code: str
    severity: Literal['INFO', 'WARNING', 'ERROR']
    message: ReasonText
    record_index: NotRequired[int]
    channel_id: NotRequired[ChannelId]
    evidence_references: list[EvidenceReference]

class CanonicalIntegrityCheck(TypedDict):
    check_id: str
    status: Literal['PASS', 'WARN', 'FAIL', 'NOT_EVALUATED']
    finding_ids: list[CanonicalIntegrityFindingId]
    evidence_references: list[EvidenceReference]

class CanonicalIntegrityReport(TypedDict):
    status: Literal['QUALIFIED', 'REVIEW_REQUIRED', 'REJECTED']
    record_count: int
    channel_count: int
    finite_value_count: int
    finding_count: int
    findings: list[CanonicalIntegrityFinding]
    checks: list[CanonicalIntegrityCheck]

class CanonicalSignalArtifact(TypedDict):
    content_hash: Sha256
    storage_key: NonEmptyString
    byte_size: int
    media_type: str
    encoding: Literal['MEF_CANONICAL_SIGNAL_NDJSON_V0_1']
    channel_order: list[ChannelId]

class ConfigurationResolutionState(str, Enum):
    NOT_EVALUATED = 'NOT_EVALUATED'

class CanonicalizationResult(TypedDict):
    status: Literal['COMPLETE', 'PARTIAL', 'BLOCKED', 'FAILED']
    acquisition: CanonicalAcquisition
    signal_artifact: CanonicalSignalArtifact
    integrity_report: CanonicalIntegrityReport
    mapping_manifest_sha256: Sha256
    canonical_identity_sha256: Sha256

class Actor(TypedDict):
    actor_type: Literal['PRACTITIONER', 'AGENT', 'SYSTEM', 'IMPORT_PROCESS', 'PROCESSOR']
    actor_id: NonEmptyString
    role: NonEmptyString

class PractitionerActor(TypedDict):
    actor_type: Literal['PRACTITIONER']
    actor_id: NonEmptyString
    role: Literal['QUALIFIED_PRACTITIONER', 'REVIEWER', 'SUPERVISOR']

class ProcessorReference(TypedDict):
    processor_id: str
    component_version: str

class MetricDefinition(TypedDict):
    definition_id: MetricDefinitionId
    definition_version: str

class Precision(TypedDict):
    representation: Literal['EXACT', 'DECIMAL', 'INTERVAL', 'SIGNIFICANT_DIGITS', 'UNKNOWN']
    digits: NotRequired[int]

class NumericValue(TypedDict):
    value: float
    unit: Unit
    precision: Precision

class TrialOutcome(TypedDict):
    state: Literal['INCLUDED', 'EXCLUDED', 'REVIEW_REQUIRED', 'UNKNOWN', 'UNRESOLVED', 'UNSUPPORTED', 'NOT_APPLICABLE']
    reason_references: list[ReasonReference]

class PractitionerOverride(TypedDict):
    authority_type: Literal['HUMAN_PRACTITIONER']
    actor_id: NonEmptyString
    attributed_at: Timestamp
    original_state: NonEmptyString
    new_state: NonEmptyString
    reason: ReasonText
    evidence_references: list[EvidenceReference]

class Disposition(TypedDict):
    state: Literal['PROPOSED_INCLUDE', 'PROPOSED_EXCLUDE', 'REVIEW_REQUIRED', 'FINAL_INCLUDE', 'FINAL_EXCLUDE', 'UNKNOWN', 'UNRESOLVED']
    authority_type: Literal['MACHINE', 'HUMAN_PRACTITIONER']
    reason_references: list[ReasonReference]

class PractitionerDisposition(TypedDict):
    state: Literal['FINAL_INCLUDE', 'FINAL_EXCLUDE', 'REVIEW_REQUIRED']
    authority_type: Literal['HUMAN_PRACTITIONER']
    actor_id: NonEmptyString
    reason_references: list[ReasonReference]

class Uncertainty(TypedDict):
    state: Literal['KNOWN', 'UNKNOWN', 'UNRESOLVED', 'NOT_APPLICABLE']
    standard_error: NotRequired[NumericValue]
    lower: NotRequired[float]
    upper: NotRequired[float]
    evidence_references: list[EvidenceReference]

class DirectionalProbability(TypedDict):
    state: Literal['KNOWN', 'UNKNOWN', 'UNRESOLVED', 'NOT_APPLICABLE']
    probability: NotRequired[float]
    direction: Literal['INCREASED', 'DECREASED', 'NO_DIRECTION', 'UNKNOWN']
    evidence_references: list[EvidenceReference]

class PracticalThresholdInterpretation(TypedDict):
    state: Literal['ELIGIBLE', 'INELIGIBLE', 'UNKNOWN', 'UNRESOLVED', 'NOT_APPLICABLE']
    interpretation: NotRequired[Literal['ABOVE', 'BELOW', 'WITHIN', 'INDETERMINATE', 'NOT_REGISTERED', 'NOT_APPLICABLE']]
    threshold_reference: NotRequired[NonEmptyString]
    evidence_references: list[EvidenceReference]

class Diagnostic(TypedDict):
    code: Literal['INSUFFICIENT_EVIDENCE', 'REFERENCE_NOT_MATURE', 'MEASUREMENT_INELIGIBLE', 'UNCERTAINTY_UNRESOLVED', 'CONFLICTING_METADATA', 'LIMITATION_PRESENT']
    description: ReasonText
    evidence_references: list[EvidenceReference]

class Limitation(TypedDict):
    code: Literal['MISSING_ACQUISITION_SEMANTICS', 'MISSING_PROTOCOL_EVIDENCE', 'REFERENCE_IMMATURITY', 'UNCERTAINTY', 'PROCESSOR_LIMITATION', 'SCOPE_LIMITATION']
    description: ReasonText

class Integrity(TypedDict):
    algorithm: Literal['SHA-256']
    digest: Sha256
    integrity_state: Literal['DECLARED', 'VERIFIED', 'FAILED', 'UNKNOWN']
    component_version: str
    signed: bool
    verification_evidence_references: NotRequired[list[EvidenceReference]]

class SourceArtifactObjectReference(TypedDict):
    entity_type: Literal['SourceArtifact']
    object_id: SourceArtifactId

class ImportAttemptObjectReference(TypedDict):
    entity_type: Literal['ImportAttempt']
    object_id: ImportAttemptId

class CanonicalAcquisitionObjectReference(TypedDict):
    entity_type: Literal['CanonicalAcquisition']
    object_id: CanonicalAcquisitionId

class ConfigurationContractObjectReference(TypedDict):
    entity_type: Literal['ConfigurationContract']
    object_id: ConfigurationContractId

class ProtocolContractObjectReference(TypedDict):
    entity_type: Literal['ProtocolContract']
    object_id: ProtocolContractId

class TrialObjectReference(TypedDict):
    entity_type: Literal['Trial']
    object_id: TrialId

class SessionObjectReference(TypedDict):
    entity_type: Literal['Session']
    object_id: SessionId

class MetricObservationObjectReference(TypedDict):
    entity_type: Literal['MetricObservation']
    object_id: MetricObservationId

class ReferenceEpochObjectReference(TypedDict):
    entity_type: Literal['ReferenceEpoch']
    object_id: ReferenceEpochId

class InferenceResultObjectReference(TypedDict):
    entity_type: Literal['InferenceResult']
    object_id: InferenceResultId

class EvidenceManifestObjectReference(TypedDict):
    entity_type: Literal['EvidenceManifest']
    object_id: EvidenceManifestId

class PractitionerDecisionObjectReference(TypedDict):
    entity_type: Literal['PractitionerDecision']
    object_id: PractitionerDecisionId

class AgentContextObjectReference(TypedDict):
    entity_type: Literal['AgentContext']
    object_id: AgentContextId

class AuditEventObjectReference(TypedDict):
    entity_type: Literal['AuditEvent']
    object_id: AuditEventId

class CommandObjectReference(TypedDict):
    entity_type: Literal['Command']
    object_id: CommandId

class JobObjectReference(TypedDict):
    entity_type: Literal['Job']
    object_id: JobId

class JobAttemptObjectReference(TypedDict):
    entity_type: Literal['JobAttempt']
    object_id: JobAttemptId

class ProgressEventObjectReference(TypedDict):
    entity_type: Literal['ProgressEvent']
    object_id: ProgressEventId

ObjectReference: TypeAlias = SourceArtifactObjectReference | ImportAttemptObjectReference | CanonicalAcquisitionObjectReference | ConfigurationContractObjectReference | ProtocolContractObjectReference | TrialObjectReference | SessionObjectReference | MetricObservationObjectReference | ReferenceEpochObjectReference | InferenceResultObjectReference | EvidenceManifestObjectReference | PractitionerDecisionObjectReference | AgentContextObjectReference | AuditEventObjectReference | CommandObjectReference | JobObjectReference | JobAttemptObjectReference | ProgressEventObjectReference

class Membership(TypedDict):
    session_ids: list[SessionId]
    metric_observation_ids: list[MetricObservationId]
    membership_digest: Sha256

class ContextScope(TypedDict):
    workspace: ScopeSlot
    athlete: ScopeSlot
    measurement_case: ScopeSlot

class ScopeSlot(TypedDict):
    state: SemanticState
    value: NotRequired[NonEmptyString]
    reason: NotRequired[ReasonText]

class MachineRecommendation(TypedDict):
    source: Literal['SYSTEM_PROCESSOR', 'AGENT_DRAFT']
    recommendation: Literal['ACCEPT', 'REJECT', 'REVIEW_REQUIRED']
    evidence_references: list[EvidenceReference]

class SourceArtifactLifecycleState(str, Enum):
    REGISTERED = 'REGISTERED'
    VERIFIED = 'VERIFIED'
    INVALID = 'INVALID'

class ImportAttemptState(str, Enum):
    RECEIVED = 'RECEIVED'
    VALIDATING = 'VALIDATING'
    ACCEPTED = 'ACCEPTED'
    REJECTED = 'REJECTED'
    UNSUPPORTED = 'UNSUPPORTED'
    FAILED = 'FAILED'

class AcquisitionState(str, Enum):
    DECLARED = 'DECLARED'
    PARTIALLY_RESOLVED = 'PARTIALLY_RESOLVED'
    QUALIFIED = 'QUALIFIED'
    UNQUALIFIED = 'UNQUALIFIED'
    REJECTED = 'REJECTED'
    UNKNOWN = 'UNKNOWN'

class ConfigurationState(str, Enum):
    RESOLVED_QUALIFIED = 'RESOLVED_QUALIFIED'
    RESOLVED_UNQUALIFIED = 'RESOLVED_UNQUALIFIED'
    PARTIALLY_RESOLVED = 'PARTIALLY_RESOLVED'
    CONFLICTING_METADATA = 'CONFLICTING_METADATA'
    UNRESOLVED = 'UNRESOLVED'

class ProtocolState(str, Enum):
    DECLARED = 'DECLARED'
    ELIGIBLE = 'ELIGIBLE'
    INELIGIBLE = 'INELIGIBLE'
    UNRESOLVED = 'UNRESOLVED'
    REVIEW_REQUIRED = 'REVIEW_REQUIRED'

class TrialState(str, Enum):
    DECLARED = 'DECLARED'
    PENDING_REVIEW = 'PENDING_REVIEW'
    ELIGIBLE = 'ELIGIBLE'
    INELIGIBLE = 'INELIGIBLE'
    REJECTED = 'REJECTED'
    PRACTITIONER_OVERRIDDEN = 'PRACTITIONER_OVERRIDDEN'

class SessionState(str, Enum):
    DRAFT = 'DRAFT'
    MACHINE_PROPOSED = 'MACHINE_PROPOSED'
    REVIEW_REQUIRED = 'REVIEW_REQUIRED'
    HUMAN_FINAL = 'HUMAN_FINAL'
    REJECTED = 'REJECTED'
    PRACTITIONER_OVERRIDDEN = 'PRACTITIONER_OVERRIDDEN'

class ObservationState(str, Enum):
    OBSERVED = 'OBSERVED'
    UNRESOLVED = 'UNRESOLVED'
    INELIGIBLE = 'INELIGIBLE'
    UNSUPPORTED = 'UNSUPPORTED'

class EpochMaturityState(str, Enum):
    IMMATURE = 'IMMATURE'
    MATURE = 'MATURE'
    UNKNOWN = 'UNKNOWN'
    UNRESOLVED = 'UNRESOLVED'

class EpochApprovalState(str, Enum):
    NOT_REQUESTED = 'NOT_REQUESTED'
    PENDING = 'PENDING'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    UNKNOWN = 'UNKNOWN'

class InferenceState(str, Enum):
    PRODUCED = 'PRODUCED'
    INELIGIBLE = 'INELIGIBLE'
    UNRESOLVED = 'UNRESOLVED'
    FAILED = 'FAILED'
    REVIEW_REQUIRED = 'REVIEW_REQUIRED'

class ManifestState(str, Enum):
    DECLARED = 'DECLARED'
    INTEGRITY_VERIFIED = 'INTEGRITY_VERIFIED'
    INTEGRITY_FAILED = 'INTEGRITY_FAILED'
    SCOPE_INCOMPLETE = 'SCOPE_INCOMPLETE'
    REVIEW_REQUIRED = 'REVIEW_REQUIRED'

class DecisionState(str, Enum):
    DRAFT = 'DRAFT'
    RECORDED = 'RECORDED'
    REVIEW_REQUIRED = 'REVIEW_REQUIRED'
    SUPERSEDES_PRIOR = 'SUPERSEDES_PRIOR'

class DecisionValue(str, Enum):
    ACCEPT = 'ACCEPT'
    REJECT = 'REJECT'
    REVIEW_REQUIRED = 'REVIEW_REQUIRED'
    OVERRIDE = 'OVERRIDE'
    ACKNOWLEDGE = 'ACKNOWLEDGE'
    NOT_APPLICABLE = 'NOT_APPLICABLE'

class ContextState(str, Enum):
    BOUNDED = 'BOUNDED'
    PARTIALLY_BOUNDED = 'PARTIALLY_BOUNDED'
    UNKNOWN = 'UNKNOWN'
    UNRESOLVED = 'UNRESOLVED'

class AuditAction(str, Enum):
    CREATED = 'CREATED'
    VALIDATED = 'VALIDATED'
    STATE_CHANGED = 'STATE_CHANGED'
    OVERRIDDEN = 'OVERRIDDEN'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    LINKED = 'LINKED'
    UNLINKED = 'UNLINKED'
    COMMAND_ACCEPTED = 'COMMAND_ACCEPTED'
    COMMAND_IDEMPOTENT_REUSED = 'COMMAND_IDEMPOTENT_REUSED'
    JOB_CLAIMED = 'JOB_CLAIMED'
    ATTEMPT_STARTED = 'ATTEMPT_STARTED'
    PROGRESS_RECORDED = 'PROGRESS_RECORDED'
    RETRY_SCHEDULED = 'RETRY_SCHEDULED'
    CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED'
    CANCELLATION_ACKNOWLEDGED = 'CANCELLATION_ACKNOWLEDGED'
    ATTEMPT_COMPLETED = 'ATTEMPT_COMPLETED'
    JOB_SUCCEEDED = 'JOB_SUCCEEDED'
    JOB_FAILED = 'JOB_FAILED'
    JOB_CANCELED = 'JOB_CANCELED'
    UNKNOWN_OUTCOME = 'UNKNOWN_OUTCOME'
    RECONCILIATION_ACTION = 'RECONCILIATION_ACTION'

class CommandType(str, Enum):
    FIXTURE_EXECUTION = 'FIXTURE_EXECUTION'
    IMPORT = 'IMPORT'
    SCIENTIFIC_PROCESSING = 'SCIENTIFIC_PROCESSING'
    INFERENCE = 'INFERENCE'
    EVIDENCE_ASSEMBLY = 'EVIDENCE_ASSEMBLY'
    AUTHORIZED_ACTION = 'AUTHORIZED_ACTION'

class RequestedOperation(str, Enum):
    EXECUTE = 'EXECUTE'

class FixtureScenario(str, Enum):
    SUCCESS = 'SUCCESS'
    RETRY_THEN_SUCCESS = 'RETRY_THEN_SUCCESS'
    NON_RETRYABLE_FAILURE = 'NON_RETRYABLE_FAILURE'
    CANCELLABLE = 'CANCELLABLE'
    UNKNOWN_OUTCOME = 'UNKNOWN_OUTCOME'
    PROGRESS = 'PROGRESS'

class FailureCategory(str, Enum):
    RETRYABLE = 'RETRYABLE'
    NON_RETRYABLE = 'NON_RETRYABLE'
    UNKNOWN_OUTCOME = 'UNKNOWN_OUTCOME'

class RetryDecision(str, Enum):
    NOT_APPLICABLE = 'NOT_APPLICABLE'
    RETRY_SCHEDULED = 'RETRY_SCHEDULED'
    RETRY_EXHAUSTED = 'RETRY_EXHAUSTED'
    MANUAL_RECONCILIATION_REQUIRED = 'MANUAL_RECONCILIATION_REQUIRED'
    CANCELED = 'CANCELED'

class JobState(str, Enum):
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    RETRY_WAIT = 'RETRY_WAIT'
    CANCEL_REQUESTED = 'CANCEL_REQUESTED'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    CANCELED = 'CANCELED'
    UNKNOWN_OUTCOME = 'UNKNOWN_OUTCOME'

class JobAttemptOutcome(str, Enum):
    STARTED = 'STARTED'
    SUCCEEDED = 'SUCCEEDED'
    FAILED_RETRYABLE = 'FAILED_RETRYABLE'
    FAILED_NON_RETRYABLE = 'FAILED_NON_RETRYABLE'
    UNKNOWN_OUTCOME = 'UNKNOWN_OUTCOME'
    CANCELED = 'CANCELED'

class WorkerType(str, Enum):
    FIXTURE = 'FIXTURE'

class ProgressPhase(str, Enum):
    QUEUED = 'QUEUED'
    STARTING = 'STARTING'
    RUNNING = 'RUNNING'
    RETRYING = 'RETRYING'
    CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED'
    CANCELLATION_ACKNOWLEDGED = 'CANCELLATION_ACKNOWLEDGED'
    COMPLETED = 'COMPLETED'
    RECONCILING = 'RECONCILING'

class ProgressCode(str, Enum):
    COMMAND_ACCEPTED = 'COMMAND_ACCEPTED'
    ATTEMPT_STARTED = 'ATTEMPT_STARTED'
    STEP_COMPLETED = 'STEP_COMPLETED'
    RETRY_SCHEDULED = 'RETRY_SCHEDULED'
    CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED'
    CANCELLATION_ACKNOWLEDGED = 'CANCELLATION_ACKNOWLEDGED'
    ATTEMPT_COMPLETED = 'ATTEMPT_COMPLETED'
    JOB_COMPLETED = 'JOB_COMPLETED'
    OUTCOME_UNKNOWN = 'OUTCOME_UNKNOWN'
    RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED'

class ExecutionErrorCode(str, Enum):
    IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT'
    JOB_NOT_FOUND = 'JOB_NOT_FOUND'
    JOB_NOT_CLAIMABLE = 'JOB_NOT_CLAIMABLE'
    INVALID_JOB_TRANSITION = 'INVALID_JOB_TRANSITION'
    JOB_ALREADY_TERMINAL = 'JOB_ALREADY_TERMINAL'
    CANCELLATION_NOT_ALLOWED = 'CANCELLATION_NOT_ALLOWED'
    ATTEMPT_LIMIT_EXCEEDED = 'ATTEMPT_LIMIT_EXCEEDED'
    WORKER_FAILURE_RETRYABLE = 'WORKER_FAILURE_RETRYABLE'
    WORKER_FAILURE_NON_RETRYABLE = 'WORKER_FAILURE_NON_RETRYABLE'
    EXECUTION_OUTCOME_UNKNOWN = 'EXECUTION_OUTCOME_UNKNOWN'
    JOB_PERSISTENCE_FAILED = 'JOB_PERSISTENCE_FAILED'
    UNKNOWN_COMMAND_TYPE = 'UNKNOWN_COMMAND_TYPE'
    UNKNOWN_WORKER_TYPE = 'UNKNOWN_WORKER_TYPE'
    PROGRESS_SEQUENCE_CONFLICT = 'PROGRESS_SEQUENCE_CONFLICT'
    RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED'
    INVALID_COMMAND_PAYLOAD = 'INVALID_COMMAND_PAYLOAD'
    INVALID_PROGRESS_EVENT = 'INVALID_PROGRESS_EVENT'

class ReconciliationState(str, Enum):
    NONE = 'NONE'
    RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED'
    RECONCILED = 'RECONCILED'

class CommandPayload(TypedDict):
    payload_kind: Literal['STRUCTURAL']
    input_label: NonEmptyString
    input_value: ReasonText
    fixture_scenario: NotRequired[FixtureScenario]

class CorrelationMetadata(TypedDict):
    correlation_id: NonEmptyString
    request_id: NonEmptyString
    causation_id: NotRequired[NonEmptyString]

class RetryPolicy(TypedDict):
    max_attempts: int
    backoff_milliseconds: int
    backoff_strategy: Literal['FIXED']

class JobResult(TypedDict):
    result_code: Literal['COMPLETED', 'CANCELED']
    summary_code: NonEmptyString
    result_reference: NotRequired[ObjectReference]

class ExecutionError(TypedDict):
    code: ExecutionErrorCode
    category: FailureCategory

class JobCancellation(TypedDict):
    requested_at: Timestamp
    acknowledged_at: NotRequired[Timestamp]
    canceled_at: NotRequired[Timestamp]
    reason_code: Literal['USER_REQUESTED', 'SAFE_BOUNDARY']

class SourceArtifact(TypedDict):
    entity_type: Literal['SourceArtifact']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/source-artifact.schema.json']
    schema_version: SchemaVersion
    source_artifact_id: SourceArtifactId
    record_version: int
    created_at: Timestamp
    lifecycle_state: SourceArtifactLifecycleState
    content_hash: Sha256
    byte_size: int
    media_type: str
    original_filename: NonEmptyString
    ingested_at: Timestamp
    source_declaration: SemanticDeclaration
    immutable_source: Literal[True]

class ImportAttempt(TypedDict):
    entity_type: Literal['ImportAttempt']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/import-attempt.schema.json']
    schema_version: SchemaVersion
    import_attempt_id: ImportAttemptId
    record_version: int
    source_artifact_id: SourceArtifactId
    attempt_number: int
    attempted_at: Timestamp
    attempt_state: ImportAttemptState
    errors: list[ContractError]

class CanonicalAcquisition(TypedDict):
    entity_type: Literal['CanonicalAcquisition']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/canonical-acquisition.schema.json']
    schema_version: SchemaVersion
    canonical_acquisition_id: CanonicalAcquisitionId
    record_version: int
    created_at: Timestamp
    source_artifact_id: SourceArtifactId
    source_observation_id: SourceObservationId
    source_observation_sha256: Sha256
    canonicalizer_version: str
    mapping_manifest_sha256: Sha256
    signal_artifact_sha256: Sha256
    integrity_report_sha256: Sha256
    canonical_identity_sha256: Sha256
    acquisition_state: AcquisitionState
    modality: SemanticDeclaration
    channels: list[CanonicalChannel]
    source_mappings: list[CanonicalSourceMapping]
    sample_semantics: SemanticDeclaration
    timebase: CanonicalTimebase
    synchronization: SemanticDeclaration
    calibration: SemanticDeclaration
    preprocessing: SemanticDeclaration
    missingness_quality: SemanticDeclaration
    configuration_resolution: ConfigurationResolutionState
    manifest: CanonicalAcquisitionManifest
    signal_artifact: CanonicalSignalArtifact
    integrity_report: CanonicalIntegrityReport
    quality_state: QualityState
    blocking_reasons: list[ReasonReference]

class AcquisitionConfigurationContract(TypedDict):
    contract: Literal['single.total_fz', 'dual.independent_fz', 'UNKNOWN', 'UNSUPPORTED']
    state: Literal['RESOLVED', 'UNKNOWN', 'UNSUPPORTED', 'CONFLICTING']
    evidence_references: list[ConfigurationEvidenceReference]

class ChannelCapability(TypedDict):
    channel_id: ChannelId
    physical_quantity: SemanticDeclaration
    axis: SemanticDeclaration
    sign: SemanticDeclaration
    plate_identity: SemanticDeclaration
    sample_count: int
    evidence_references: list[ConfigurationEvidenceReference]

class SampleRateResolution(TypedDict):
    state: Literal['RESOLVED', 'UNKNOWN', 'CONFLICTING']
    sample_rate_hz: NotRequired[float]
    interval_seconds: NotRequired[float]
    source: Literal['EXPLICIT_SOURCE_DECLARATION', 'CANONICAL_TIMEBASE', 'EXACT_TIMESTAMP_INTERVAL', 'UNKNOWN']
    evidence_references: list[ConfigurationEvidenceReference]

class SynchronizationResolution(TypedDict):
    state: Literal['SYNCHRONIZED', 'UNSYNCHRONIZED', 'UNKNOWN', 'CONFLICTING', 'NOT_APPLICABLE']
    evidence_references: list[ConfigurationEvidenceReference]

class AxisSignResolution(TypedDict):
    state: Literal['RESOLVED', 'UNKNOWN', 'CONFLICTING']
    axis: NotRequired[NonEmptyString]
    sign: NotRequired[NonEmptyString]
    evidence_references: list[ConfigurationEvidenceReference]

class PreprocessingResolution(TypedDict):
    state: Literal['NONE_DECLARED', 'DECLARED', 'UNKNOWN', 'CONFLICTING']
    description: NotRequired[ReasonText]
    evidence_references: list[ConfigurationEvidenceReference]

class CalibrationResolution(TypedDict):
    state: Literal['CONFIRMED', 'DECLARED', 'UNKNOWN', 'CONFLICTING', 'NOT_APPLICABLE']
    description: NotRequired[ReasonText]
    evidence_references: list[ConfigurationEvidenceReference]

class ZeroingResolution(TypedDict):
    state: Literal['CONFIRMED', 'DECLARED', 'UNKNOWN', 'CONFLICTING', 'NOT_APPLICABLE']
    description: NotRequired[ReasonText]
    evidence_references: list[ConfigurationEvidenceReference]

class ProtocolEligibilityResolution(TypedDict):
    state: Literal['ELIGIBLE', 'INELIGIBLE', 'UNRESOLVED', 'NOT_EVALUATED']
    authority_version: NonEmptyString
    evidence_references: list[ConfigurationEvidenceReference]

class ConfigurationFinding(TypedDict):
    code: str
    severity: Literal['INFO', 'WARNING', 'ERROR']
    message: ReasonText
    evidence_references: list[ConfigurationEvidenceReference]

class ConfigurationEvidenceReference(TypedDict):
    source_artifact_id: SourceArtifactId
    source_observation_id: SourceObservationId
    canonical_acquisition_id: CanonicalAcquisitionId
    channel_id: NotRequired[ChannelId]
    locator: NonEmptyString
    content_hash: Sha256

class AcquisitionConfigurationResolution(TypedDict):
    resolver_version: str
    authority_version: NonEmptyString
    source_artifact_id: SourceArtifactId
    source_observation_id: SourceObservationId
    canonical_acquisition_id: CanonicalAcquisitionId
    canonical_identity_sha256: Sha256
    evidence_manifest_sha256: NotRequired[Sha256]
    configuration_state: ConfigurationState
    physical_contract: AcquisitionConfigurationContract
    channel_capabilities: list[ChannelCapability]
    sample_rate: SampleRateResolution
    synchronization: SynchronizationResolution
    axis_sign: AxisSignResolution
    preprocessing: PreprocessingResolution
    calibration: CalibrationResolution
    zeroing: ZeroingResolution
    protocol_eligibility: ProtocolEligibilityResolution
    findings: list[ConfigurationFinding]
    evidence_references: list[ConfigurationEvidenceReference]
    resolution_sha256: Sha256

class ConfigurationContract(TypedDict):
    entity_type: Literal['ConfigurationContract']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/configuration-contract.schema.json']
    schema_version: SchemaVersion
    configuration_contract_id: ConfigurationContractId
    record_version: int
    created_at: Timestamp
    canonical_acquisition_id: CanonicalAcquisitionId
    configuration_state: ConfigurationState
    configuration_name: SemanticDeclaration
    qualification_evidence_references: list[EvidenceReference]
    reason_references: list[ReasonReference]
    resolution: NotRequired[AcquisitionConfigurationResolution]

class ProtocolContract(TypedDict):
    entity_type: Literal['ProtocolContract']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/protocol-contract.schema.json']
    schema_version: SchemaVersion
    protocol_contract_id: ProtocolContractId
    record_version: int
    created_at: Timestamp
    protocol_key: Literal['bilateral-unloaded-hands-on-hips-countermovement-jump']
    protocol_version: str
    protocol_state: ProtocolState
    bilateral: ConditionObservation
    unloaded: ConditionObservation
    hands_on_hips: ConditionObservation
    countermovement_jump: ConditionObservation
    eligibility_evidence_references: list[EvidenceReference]

class Trial(TypedDict):
    entity_type: Literal['Trial']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/trial.schema.json']
    schema_version: SchemaVersion
    trial_id: TrialId
    record_version: int
    created_at: Timestamp
    trial_state: TrialState
    canonical_acquisition_id: CanonicalAcquisitionId
    protocol_contract_id: ProtocolContractId
    session_id: NotRequired[SessionId]
    quality_state: QualityState
    original_outcome: TrialOutcome
    practitioner_override: NotRequired[PractitionerOverride]
    event_evidence_references: list[EvidenceReference]
    eligibility_evidence_references: list[EvidenceReference]

class Session(TypedDict):
    entity_type: Literal['Session']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/session.schema.json']
    schema_version: SchemaVersion
    session_id: SessionId
    record_version: int
    created_at: Timestamp
    session_state: SessionState
    contributing_trial_ids: list[TrialId]
    machine_proposed_disposition: Disposition
    human_final_disposition: NotRequired[PractitionerDisposition]
    review_references: list[EvidenceReference]

class MetricObservation(TypedDict):
    entity_type: Literal['MetricObservation']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/metric-observation.schema.json']
    schema_version: SchemaVersion
    metric_observation_id: MetricObservationId
    record_version: int
    created_at: Timestamp
    metric_definition: MetricDefinition
    value: NumericValue
    processor: ProcessorReference
    contributing_trial_ids: list[TrialId]
    contributing_session_id: NotRequired[SessionId]
    observation_state: ObservationState
    eligibility_state: QualityState
    evidence_references: list[EvidenceReference]

class ReferenceEpoch(TypedDict):
    entity_type: Literal['ReferenceEpoch']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/reference-epoch.schema.json']
    schema_version: SchemaVersion
    reference_epoch_id: ReferenceEpochId
    record_version: int
    created_at: Timestamp
    reference_policy_id: str
    reference_policy_version: str
    membership: Membership
    maturity_state: EpochMaturityState
    approval_state: EpochApprovalState
    membership_evidence_references: list[EvidenceReference]
    approval_decision_id: NotRequired[PractitionerDecisionId]
    approval_evidence_references: NotRequired[list[EvidenceReference]]

class InferenceResult(TypedDict):
    entity_type: Literal['InferenceResult']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/inference-result.schema.json']
    schema_version: SchemaVersion
    inference_result_id: InferenceResultId
    record_version: int
    created_at: Timestamp
    metric_observation_id: MetricObservationId
    reference_epoch_id: ReferenceEpochId
    inference_state: InferenceState
    measurement_estimate: NumericValue
    uncertainty: Uncertainty
    directional_probability: DirectionalProbability
    practical_threshold_interpretation: PracticalThresholdInterpretation
    diagnostics: list[Diagnostic]
    eligibility_state: QualityState
    limitations: list[Limitation]

class EvidenceManifest(TypedDict):
    entity_type: Literal['EvidenceManifest']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/evidence-manifest.schema.json']
    schema_version: SchemaVersion
    evidence_manifest_id: EvidenceManifestId
    record_version: int
    created_at: Timestamp
    manifest_version: str
    manifest_state: ManifestState
    source_artifact_ids: list[SourceArtifactId]
    configuration_contract_ids: list[ConfigurationContractId]
    protocol_contract_ids: list[ProtocolContractId]
    processors: list[ProcessorReference]
    metric_observation_ids: list[MetricObservationId]
    session_ids: list[SessionId]
    reference_epoch_ids: list[ReferenceEpochId]
    inference_result_ids: list[InferenceResultId]
    practitioner_decision_ids: list[PractitionerDecisionId]
    integrity: Integrity
    component_version: str

class PractitionerDecision(TypedDict):
    entity_type: Literal['PractitionerDecision']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/practitioner-decision.schema.json']
    schema_version: SchemaVersion
    practitioner_decision_id: PractitionerDecisionId
    record_version: int
    created_at: Timestamp
    decision_state: DecisionState
    authority_type: Literal['HUMAN_PRACTITIONER']
    actor: PractitionerActor
    decided_at: Timestamp
    decision: DecisionValue
    rationale: ReasonText
    target: ObjectReference
    evidence_manifest_ids: list[EvidenceManifestId]
    machine_recommendation: NotRequired[MachineRecommendation]

class AgentContext(TypedDict):
    entity_type: Literal['AgentContext']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/agent-context.schema.json']
    schema_version: SchemaVersion
    agent_context_id: AgentContextId
    record_version: int
    created_at: Timestamp
    context_state: ContextState
    scope: ContextScope
    screen_object_context: ScopeSlot
    selected_evidence_manifest_ids: list[EvidenceManifestId]
    unresolved_warnings: list[ReasonText]

class Command(TypedDict):
    entity_type: Literal['Command']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/command.schema.json']
    schema_version: SchemaVersion
    command_id: CommandId
    record_version: int
    command_type: CommandType
    idempotency_key: IdempotencyKey
    semantic_input_digest: Sha256
    submitted_at: Timestamp
    request_payload: CommandPayload
    requested_operation: RequestedOperation
    request_reference: NotRequired[ObjectReference]
    authority_context_reference: ObjectReference
    correlation_metadata: CorrelationMetadata

class Job(TypedDict):
    entity_type: Literal['Job']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/job.schema.json']
    schema_version: SchemaVersion
    job_id: JobId
    record_version: int
    command_id: CommandId
    created_at: Timestamp
    queued_at: Timestamp
    started_at: NotRequired[Timestamp]
    updated_at: Timestamp
    finished_at: NotRequired[Timestamp]
    state: JobState
    retry_policy: RetryPolicy
    current_attempt_number: int
    next_eligible_attempt_at: NotRequired[Timestamp]
    last_attempt_id: NotRequired[JobAttemptId]
    cancellation: NotRequired[JobCancellation]
    reconciliation_state: ReconciliationState
    result: NotRequired[JobResult]
    error: NotRequired[ExecutionError]

class JobAttempt(TypedDict):
    entity_type: Literal['JobAttempt']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/job-attempt.schema.json']
    schema_version: SchemaVersion
    job_attempt_id: JobAttemptId
    record_version: int
    job_id: JobId
    attempt_number: int
    worker_identity: str
    worker_type: WorkerType
    claimed_at: Timestamp
    started_at: NotRequired[Timestamp]
    ended_at: NotRequired[Timestamp]
    lease_expires_at: NotRequired[Timestamp]
    outcome: JobAttemptOutcome
    failure_category: NotRequired[FailureCategory]
    retry_decision: RetryDecision
    cancellation_acknowledged_at: NotRequired[Timestamp]
    result: NotRequired[JobResult]
    error: NotRequired[ExecutionError]

class ProgressEvent(TypedDict):
    entity_type: Literal['ProgressEvent']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/progress-event.schema.json']
    schema_version: SchemaVersion
    progress_event_id: ProgressEventId
    record_version: int
    job_id: JobId
    job_attempt_id: NotRequired[JobAttemptId]
    sequence: int
    occurred_at: Timestamp
    phase: ProgressPhase
    message_code: ProgressCode
    progress_value: NotRequired[float]

class AuditEvent(TypedDict):
    entity_type: Literal['AuditEvent']
    schema_id: Literal['https://schemas.sportsagentslab.local/mef/1.0.0/audit-event.schema.json']
    schema_version: SchemaVersion
    audit_event_id: AuditEventId
    record_version: int
    occurred_at: Timestamp
    actor: Actor
    audit_action: AuditAction
    object: ObjectReference
    authority_type: Literal['SYSTEM', 'MACHINE', 'HUMAN_PRACTITIONER', 'AGENT_DRAFT']
    reason: ReasonText
    prior_reference: NotRequired[ObjectReference]
    new_reference: NotRequired[ObjectReference]
    immutable_history: Literal[True]

EntityRecord: TypeAlias = SourceArtifact | ImportAttempt | CanonicalAcquisition | ConfigurationContract | ProtocolContract | Trial | Session | MetricObservation | ReferenceEpoch | InferenceResult | EvidenceManifest | PractitionerDecision | AgentContext | AuditEvent | Command | Job | JobAttempt | ProgressEvent
