"""Generated by scripts/generate_models.py. Do not edit manually."""

# fmt: off
# ruff: noqa: E701,E702

from __future__ import annotations

import json
import math
import re
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import cast

from .models import SourceArtifact, ImportAttempt, CanonicalAcquisition, ConfigurationContract, ProtocolContract, Trial, Session, MetricObservation, ReferenceEpoch, InferenceResult, EvidenceManifest, PractitionerDecision, AgentContext, AuditEvent, Command, Job, JobAttempt, ProgressEvent, SourceArtifactId, ImportAttemptId, CanonicalAcquisitionId, ConfigurationContractId, ProtocolContractId, TrialId, SessionId, MetricObservationId, ReferenceEpochId, InferenceResultId, EvidenceManifestId, PractitionerDecisionId, AgentContextId, AuditEventId, CommandId, JobId, JobAttemptId, ProgressEventId, SourceObservationId, CanonicalMappingManifestId, CanonicalIntegrityFindingId, SemanticState, QualityState, EntityType, ErrorCode, ConfigurationResolutionState, SourceArtifactLifecycleState, ImportAttemptState, AcquisitionState, ConfigurationState, ProtocolState, TrialState, SessionState, ObservationState, EpochMaturityState, EpochApprovalState, InferenceState, ManifestState, DecisionState, DecisionValue, ContextState, AuditAction, CommandType, RequestedOperation, FixtureScenario, FailureCategory, RetryDecision, JobState, JobAttemptOutcome, WorkerType, ProgressPhase, ProgressCode, ExecutionErrorCode, ReconciliationState, ContractError, EntityRecord
from .schema_data import SCHEMA_DOCUMENT

ENTITY_TYPES = frozenset(('SourceArtifact', 'ImportAttempt', 'CanonicalAcquisition', 'ConfigurationContract', 'ProtocolContract', 'Trial', 'Session', 'MetricObservation', 'ReferenceEpoch', 'InferenceResult', 'EvidenceManifest', 'PractitionerDecision', 'AgentContext', 'AuditEvent', 'Command', 'Job', 'JobAttempt', 'ProgressEvent'))
FORBIDDEN_FIELD_TOKENS = ('readiness', 'fatigue', 'recovery', 'injury', 'diagnosis', 'clearance', 'causal_training_effect', 'training_prescription')
ENTITY_SCHEMAS: dict[str, dict[str, object]] = {
    "SourceArtifact": SCHEMA_DOCUMENT["$defs"]["SourceArtifact"],
    "ImportAttempt": SCHEMA_DOCUMENT["$defs"]["ImportAttempt"],
    "CanonicalAcquisition": SCHEMA_DOCUMENT["$defs"]["CanonicalAcquisition"],
    "ConfigurationContract": SCHEMA_DOCUMENT["$defs"]["ConfigurationContract"],
    "ProtocolContract": SCHEMA_DOCUMENT["$defs"]["ProtocolContract"],
    "Trial": SCHEMA_DOCUMENT["$defs"]["Trial"],
    "Session": SCHEMA_DOCUMENT["$defs"]["Session"],
    "MetricObservation": SCHEMA_DOCUMENT["$defs"]["MetricObservation"],
    "ReferenceEpoch": SCHEMA_DOCUMENT["$defs"]["ReferenceEpoch"],
    "InferenceResult": SCHEMA_DOCUMENT["$defs"]["InferenceResult"],
    "EvidenceManifest": SCHEMA_DOCUMENT["$defs"]["EvidenceManifest"],
    "PractitionerDecision": SCHEMA_DOCUMENT["$defs"]["PractitionerDecision"],
    "AgentContext": SCHEMA_DOCUMENT["$defs"]["AgentContext"],
    "AuditEvent": SCHEMA_DOCUMENT["$defs"]["AuditEvent"],
    "Command": SCHEMA_DOCUMENT["$defs"]["Command"],
    "Job": SCHEMA_DOCUMENT["$defs"]["Job"],
    "JobAttempt": SCHEMA_DOCUMENT["$defs"]["JobAttempt"],
    "ProgressEvent": SCHEMA_DOCUMENT["$defs"]["ProgressEvent"]
}
ID_CLASSES: dict[str, type[str]] = {"SourceArtifactId": SourceArtifactId, "ImportAttemptId": ImportAttemptId, "CanonicalAcquisitionId": CanonicalAcquisitionId, "ConfigurationContractId": ConfigurationContractId, "ProtocolContractId": ProtocolContractId, "TrialId": TrialId, "SessionId": SessionId, "MetricObservationId": MetricObservationId, "ReferenceEpochId": ReferenceEpochId, "InferenceResultId": InferenceResultId, "EvidenceManifestId": EvidenceManifestId, "PractitionerDecisionId": PractitionerDecisionId, "AgentContextId": AgentContextId, "AuditEventId": AuditEventId, "CommandId": CommandId, "JobId": JobId, "JobAttemptId": JobAttemptId, "ProgressEventId": ProgressEventId, "SourceObservationId": SourceObservationId, "CanonicalMappingManifestId": CanonicalMappingManifestId, "CanonicalIntegrityFindingId": CanonicalIntegrityFindingId}
ENUM_CLASSES: dict[str, type[Enum]] = {"SemanticState": SemanticState, "QualityState": QualityState, "EntityType": EntityType, "ErrorCode": ErrorCode, "ConfigurationResolutionState": ConfigurationResolutionState, "SourceArtifactLifecycleState": SourceArtifactLifecycleState, "ImportAttemptState": ImportAttemptState, "AcquisitionState": AcquisitionState, "ConfigurationState": ConfigurationState, "ProtocolState": ProtocolState, "TrialState": TrialState, "SessionState": SessionState, "ObservationState": ObservationState, "EpochMaturityState": EpochMaturityState, "EpochApprovalState": EpochApprovalState, "InferenceState": InferenceState, "ManifestState": ManifestState, "DecisionState": DecisionState, "DecisionValue": DecisionValue, "ContextState": ContextState, "AuditAction": AuditAction, "CommandType": CommandType, "RequestedOperation": RequestedOperation, "FixtureScenario": FixtureScenario, "FailureCategory": FailureCategory, "RetryDecision": RetryDecision, "JobState": JobState, "JobAttemptOutcome": JobAttemptOutcome, "WorkerType": WorkerType, "ProgressPhase": ProgressPhase, "ProgressCode": ProgressCode, "ExecutionErrorCode": ExecutionErrorCode, "ReconciliationState": ReconciliationState}


@dataclass(frozen=True)
class ValidationResult:
    valid: bool
    errors: tuple[ContractError, ...]


class ContractValidationError(ValueError):
    def __init__(self, errors: tuple[ContractError, ...]) -> None:
        self.errors = errors
        super().__init__("; ".join(f"{error['code']}:{error['path']}" for error in errors))


def canonical_json(value: object) -> str:
    return _encode_canonical(value)


def _format_number(value: int | float) -> str:
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if not math.isfinite(float(value)):
        raise ValueError("canonical JSON cannot encode a non-finite number")
    if value == 0:
        return "0"
    text = repr(float(value)).lower()
    if "e" not in text:
        return text[:-2] if text.endswith(".0") else text
    mantissa, exponent_text = text.split("e", 1)
    exponent = int(exponent_text)
    magnitude = abs(float(value))
    if 1e-6 <= magnitude < 1e21:
        fixed = format(Decimal(text), "f")
        if "." in fixed:
            fixed = fixed.rstrip("0").rstrip(".")
        return fixed
    mantissa = mantissa.rstrip("0").rstrip(".")
    return f"{mantissa}e{exponent:+d}"


def _encode_canonical(value: object) -> str:
    if isinstance(value, Enum):
        return _encode_canonical(value.value)
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return _format_number(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, Mapping):
        entries = ",".join(
            json.dumps(str(key), ensure_ascii=False) + ":" + _encode_canonical(item)
            for key, item in sorted(value.items(), key=lambda item: str(item[0]))
        )
        return "{" + entries + "}"
    if isinstance(value, list):
        return "[" + ",".join(_encode_canonical(item) for item in value) + "]"
    if isinstance(value, tuple):
        return "[" + ",".join(_encode_canonical(item) for item in value) + "]"
    raise TypeError("canonical JSON cannot encode this value")


def _error(code: str, message: str, path: str) -> ContractError:
    return cast(ContractError, {"taxonomy_version": "1.0.0", "code": code, "message": message, "path": path})


def _error_code(path: str, keyword: str) -> str:
    if keyword == "required": return "MISSING_REQUIRED_FIELD"
    if keyword == "additionalProperties":
        if any(token in path.lower() for token in FORBIDDEN_FIELD_TOKENS): return "FORBIDDEN_FIELD"
        return "UNKNOWN_GOVERNED_FIELD"
    if keyword in {"enum", "const"}:
        if path.endswith("schema_version"): return "UNSUPPORTED_SCHEMA_VERSION"
        if path.endswith("schema_id"): return "INCOMPATIBLE_CONTRACT_VERSION"
        if path.endswith("authority_type") or path.endswith("actor.actor_type"): return "FORBIDDEN_AUTHORITY_COMBINATION"
        return "UNKNOWN_ENUM_VALUE"
    if keyword == "pattern":
        if "evidence" in path: return "INVALID_EVIDENCE_REFERENCE"
        if path.endswith("_id") or path.endswith("object_id"): return "INVALID_IDENTIFIER"
        if "hash" in path or path.endswith("digest"): return "INVALID_HASH"
        if "timestamp" in path or path.endswith("_at"): return "INVALID_TIMESTAMP"
        if "unit" in path: return "INVALID_UNIT"
    if keyword == "format" and ("timestamp" in path or path.endswith("_at")): return "INVALID_TIMESTAMP"
    if keyword == "type": return "INVALID_TYPE"
    return "VALIDATION_ERROR"


def _resolve(schema: Mapping[str, object]) -> Mapping[str, object]:
    reference = schema.get("$ref")
    if isinstance(reference, str) and reference.startswith("#/$defs/"):
        resolved = SCHEMA_DOCUMENT["$defs"][reference[len("#/$defs/"):]]
        if isinstance(resolved, Mapping): return resolved
    return schema


def _validate(value: object, raw_schema: Mapping[str, object], path: str, errors: list[ContractError]) -> None:
    schema = _resolve(raw_schema)
    all_of = schema.get("allOf")
    if isinstance(all_of, list):
        for candidate in all_of:
            if isinstance(candidate, Mapping):
                _validate(value, cast(Mapping[str, object], candidate), path, errors)
    if_schema = schema.get("if")
    if isinstance(if_schema, Mapping):
        condition_errors: list[ContractError] = []
        _validate(value, cast(Mapping[str, object], if_schema), path, condition_errors)
        then_schema = schema.get("then")
        if not condition_errors and isinstance(then_schema, Mapping):
            _validate(value, cast(Mapping[str, object], then_schema), path, errors)
    not_schema = schema.get("not")
    if isinstance(not_schema, Mapping):
        forbidden_errors: list[ContractError] = []
        _validate(value, cast(Mapping[str, object], not_schema), path, forbidden_errors)
        if not forbidden_errors:
            errors.append(_error("VALIDATION_ERROR", "value matched a forbidden schema", path))
    any_of = schema.get("anyOf")
    if isinstance(any_of, list):
        successes = 0
        for candidate in any_of:
            if not isinstance(candidate, Mapping):
                continue
            any_candidate_errors: list[ContractError] = []
            _validate(value, cast(Mapping[str, object], candidate), path, any_candidate_errors)
            if not any_candidate_errors:
                successes += 1
        if successes == 0:
            errors.append(_error("VALIDATION_ERROR", "value did not match any governed schema", path))
    one_of = schema.get("oneOf")
    if isinstance(one_of, list):
        successes = 0
        for candidate in one_of:
            if not isinstance(candidate, Mapping): continue
            one_candidate_errors: list[ContractError] = []
            _validate(value, candidate, path, one_candidate_errors)
            if not one_candidate_errors: successes += 1
        if successes != 1:
            code = "UNRESOLVED_REFERENCE" if path.endswith(".target") or path.endswith(".object") else "VALIDATION_ERROR"
            errors.append(_error(code, "value did not match exactly one governed schema", path))
    expected_type = schema.get("type")
    applies_object_keywords = expected_type == "object" or (
        expected_type is None and isinstance(value, Mapping)
    )
    if applies_object_keywords:
        if not isinstance(value, Mapping): errors.append(_error(_error_code(path, "type"), "expected object", path)); return
        required = schema.get("required")
        if isinstance(required, list):
            for field in required:
                if isinstance(field, str) and field not in value: errors.append(_error(_error_code(path + "." + field, "required"), "missing required field", path + "." + field))
        properties = schema.get("properties")
        property_map = properties if isinstance(properties, Mapping) else {}
        if schema.get("additionalProperties") is False:
            for field in value:
                if field not in property_map: errors.append(_error(_error_code(path + "." + str(field), "additionalProperties"), "unknown governed field", path + "." + str(field)))
        for field, definition in property_map.items():
            if field in value and isinstance(definition, Mapping): _validate(value[field], definition, path + "." + str(field), errors)
    elif expected_type == "array" or (
        expected_type is None and isinstance(value, list)
    ):
        if not isinstance(value, list): errors.append(_error(_error_code(path, "type"), "expected array", path)); return
        min_items = schema.get("minItems")
        if isinstance(min_items, int) and len(value) < min_items: errors.append(_error("VALIDATION_ERROR", "array has too few items", path))
        items = schema.get("items")
        if isinstance(items, Mapping):
            for index, item in enumerate(value): _validate(item, items, f"{path}[{index}]", errors)
        contains = schema.get("contains")
        if isinstance(contains, Mapping):
            matches = False
            for item in value:
                contains_candidate_errors: list[ContractError] = []
                _validate(item, cast(Mapping[str, object], contains), path, contains_candidate_errors)
                if not contains_candidate_errors:
                    matches = True
                    break
            if not matches:
                errors.append(_error("VALIDATION_ERROR", "array contains no governed match", path))
        if schema.get("uniqueItems") is True:
            seen: set[str] = set()
            for item in value:
                digest = canonical_json(item)
                if digest in seen: errors.append(_error("VALIDATION_ERROR", "array items must be unique", path))
                seen.add(digest)
    elif expected_type == "string":
        if not isinstance(value, str): errors.append(_error(_error_code(path, "type"), "expected string", path)); return
        min_length = schema.get("minLength")
        if isinstance(min_length, int) and len(value) < min_length: errors.append(_error("VALIDATION_ERROR", "string is too short", path))
        max_length = schema.get("maxLength")
        if isinstance(max_length, int) and len(value) > max_length: errors.append(_error("VALIDATION_ERROR", "string is too long", path))
        pattern = schema.get("pattern")
        if isinstance(pattern, str) and re.fullmatch(pattern, value) is None: errors.append(_error(_error_code(path, "pattern"), "string does not match governed pattern", path))
        if schema.get("format") == "date-time":
            try: datetime.fromisoformat(value.replace("Z", "+00:00"))
            except ValueError: errors.append(_error(_error_code(path, "format"), "timestamp is not canonical UTC", path))
    elif expected_type == "integer":
        if isinstance(value, bool) or not isinstance(value, int): errors.append(_error(_error_code(path, "type"), "expected integer", path)); return
        minimum = schema.get("minimum")
        if isinstance(minimum, (int, float)) and value < minimum: errors.append(_error("VALIDATION_ERROR", "number is below minimum", path))
        maximum = schema.get("maximum")
        if isinstance(maximum, (int, float)) and value > maximum: errors.append(_error("VALIDATION_ERROR", "number is above maximum", path))
    elif expected_type == "number":
        if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(float(value)): errors.append(_error(_error_code(path, "type"), "expected finite number", path)); return
        minimum = schema.get("minimum")
        if isinstance(minimum, (int, float)) and value < minimum: errors.append(_error("VALIDATION_ERROR", "number is below minimum", path))
        maximum = schema.get("maximum")
        if isinstance(maximum, (int, float)) and value > maximum: errors.append(_error("VALIDATION_ERROR", "number is above maximum", path))
    elif expected_type == "boolean" and not isinstance(value, bool):
        errors.append(_error(_error_code(path, "type"), "expected boolean", path))
    enum = schema.get("enum")
    if isinstance(enum, list) and not any(type(value) is type(candidate) and value == candidate for candidate in enum):
        errors.append(_error(_error_code(path, "enum"), "unknown governed enum value", path))
    if "const" in schema:
        expected = schema["const"]
        if type(value) is not type(expected) or value != expected:
            errors.append(_error(_error_code(path, "const"), "value does not match governed constant", path))


def validate_entity(value: object, entity_type: str | None = None) -> ValidationResult:
    if not isinstance(value, Mapping): return ValidationResult(False, (_error("INVALID_TYPE", "entity must be an object", "$"),))
    actual = value.get("entity_type")
    if not isinstance(actual, str) or actual not in ENTITY_TYPES: return ValidationResult(False, (_error("UNKNOWN_ENTITY_TYPE", "unknown entity type", "$.entity_type"),))
    if entity_type is not None and actual != entity_type: return ValidationResult(False, (_error("VALIDATION_ERROR", "entity type does not match requested validator", "$.entity_type"),))
    errors: list[ContractError] = []
    _validate(value, {"$ref": f"#/$defs/{actual}"}, "$", errors)
    return ValidationResult(not errors, tuple(errors))


def _coerce(value: object, raw_schema: Mapping[str, object]) -> object:
    schema = _resolve(raw_schema)
    reference = raw_schema.get("$ref")
    if isinstance(reference, str) and reference.startswith("#/$defs/"):
        name = reference[len("#/$defs/"):]
        if name in ID_CLASSES and isinstance(value, str): return ID_CLASSES[name](value)
        if name in ENUM_CLASSES and isinstance(value, str): return ENUM_CLASSES[name](value)
    items = schema.get("items")
    if isinstance(value, list) and schema.get("type") == "array" and isinstance(items, Mapping):
        item_schema = cast(Mapping[str, object], items)
        return [_coerce(item, item_schema) for item in value]
    properties = schema.get("properties")
    if isinstance(value, Mapping) and schema.get("type") == "object" and isinstance(properties, Mapping):
        property_map = cast(Mapping[str, object], properties)
        output: dict[str, object] = {}
        for key, item in value.items():
            field = str(key)
            definition = property_map.get(field)
            if isinstance(definition, Mapping):
                output[field] = _coerce(item, cast(Mapping[str, object], definition))
            else:
                output[field] = item
        return output
    return value


def _parse(value: object, entity_type: str) -> object:
    result = validate_entity(value, entity_type)
    if not result.valid: raise ContractValidationError(result.errors)
    return _coerce(value, {"$ref": f"#/$defs/{entity_type}"})


def parse_entity(value: object) -> EntityRecord:
    if not isinstance(value, Mapping):
        raise ContractValidationError((_error("INVALID_TYPE", "entity must be an object", "$"),))
    entity_type = value.get("entity_type")
    if not isinstance(entity_type, str):
        raise ContractValidationError((_error("UNKNOWN_ENTITY_TYPE", "unknown entity type", "$.entity_type"),))
    return cast(EntityRecord, _parse(value, entity_type))


def parse_source_artifact(value: object) -> SourceArtifact:
    return cast(SourceArtifact, _parse(value, "SourceArtifact"))

def parse_import_attempt(value: object) -> ImportAttempt:
    return cast(ImportAttempt, _parse(value, "ImportAttempt"))

def parse_canonical_acquisition(value: object) -> CanonicalAcquisition:
    return cast(CanonicalAcquisition, _parse(value, "CanonicalAcquisition"))

def parse_configuration_contract(value: object) -> ConfigurationContract:
    return cast(ConfigurationContract, _parse(value, "ConfigurationContract"))

def parse_protocol_contract(value: object) -> ProtocolContract:
    return cast(ProtocolContract, _parse(value, "ProtocolContract"))

def parse_trial(value: object) -> Trial:
    return cast(Trial, _parse(value, "Trial"))

def parse_session(value: object) -> Session:
    return cast(Session, _parse(value, "Session"))

def parse_metric_observation(value: object) -> MetricObservation:
    return cast(MetricObservation, _parse(value, "MetricObservation"))

def parse_reference_epoch(value: object) -> ReferenceEpoch:
    return cast(ReferenceEpoch, _parse(value, "ReferenceEpoch"))

def parse_inference_result(value: object) -> InferenceResult:
    return cast(InferenceResult, _parse(value, "InferenceResult"))

def parse_evidence_manifest(value: object) -> EvidenceManifest:
    return cast(EvidenceManifest, _parse(value, "EvidenceManifest"))

def parse_practitioner_decision(value: object) -> PractitionerDecision:
    return cast(PractitionerDecision, _parse(value, "PractitionerDecision"))

def parse_agent_context(value: object) -> AgentContext:
    return cast(AgentContext, _parse(value, "AgentContext"))

def parse_audit_event(value: object) -> AuditEvent:
    return cast(AuditEvent, _parse(value, "AuditEvent"))

def parse_command(value: object) -> Command:
    return cast(Command, _parse(value, "Command"))

def parse_job(value: object) -> Job:
    return cast(Job, _parse(value, "Job"))

def parse_job_attempt(value: object) -> JobAttempt:
    return cast(JobAttempt, _parse(value, "JobAttempt"))

def parse_progress_event(value: object) -> ProgressEvent:
    return cast(ProgressEvent, _parse(value, "ProgressEvent"))
