name: Public build and test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: "3.12"
      - run: python -m unittest discover -s tests -p "test_*.py"
      - run: python examples/cmj/run_demo.py
